/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddonsGroupInfoRowGroupInfoItem model module.
 * @module model/AddonsGroupInfoRowGroupInfoItem
 * @version 0.1.0
 */
class AddonsGroupInfoRowGroupInfoItem {
    /**
     * Constructs a new <code>AddonsGroupInfoRowGroupInfoItem</code>.
     * @alias module:model/AddonsGroupInfoRowGroupInfoItem
     */
    constructor() { 
        
        AddonsGroupInfoRowGroupInfoItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddonsGroupInfoRowGroupInfoItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddonsGroupInfoRowGroupInfoItem} obj Optional instance to populate.
     * @return {module:model/AddonsGroupInfoRowGroupInfoItem} The populated <code>AddonsGroupInfoRowGroupInfoItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddonsGroupInfoRowGroupInfoItem();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddonsGroupInfoRowGroupInfoItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddonsGroupInfoRowGroupInfoItem</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getTitle() {
        return this.title;
    }

    /**
     * @param {String} title
     */
    setTitle(title) {
        this['title'] = title;
    }
/**
     * @return {String}
     */
    getValue() {
        return this.value;
    }

    /**
     * @param {String} value
     */
    setValue(value) {
        this['value'] = value;
    }

}



/**
 * @member {String} title
 */
AddonsGroupInfoRowGroupInfoItem.prototype['title'] = undefined;

/**
 * @member {String} value
 */
AddonsGroupInfoRowGroupInfoItem.prototype['value'] = undefined;






export default AddonsGroupInfoRowGroupInfoItem;

