/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AddonSecondaryLinkagePosition.
* @enum {}
* @readonly
*/
export default class AddonSecondaryLinkagePosition {
    
        /**
         * value: "POST_SPEC_HEAD"
         * @const
         */
        "SPEC_HEAD" = "POST_SPEC_HEAD";

    
        /**
         * value: "POST_SPEC_TAIL"
         * @const
         */
        "SPEC_TAIL" = "POST_SPEC_TAIL";

    
        /**
         * value: "POST_PRICE_SPEC"
         * @const
         */
        "PRICE_SPEC" = "POST_PRICE_SPEC";

    
        /**
         * value: "POST_DESC_TAIL"
         * @const
         */
        "DESC_TAIL" = "POST_DESC_TAIL";

    

    /**
    * Returns a <code>AddonSecondaryLinkagePosition</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AddonSecondaryLinkagePosition} The enum <code>AddonSecondaryLinkagePosition</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

