/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddonSemanticCarVerificationStage from './AddonSemanticCarVerificationStage';
import AddonSemanticIdentityVerificationResult from './AddonSemanticIdentityVerificationResult';
import AddonSemanticIdentityVerificationStage from './AddonSemanticIdentityVerificationStage';
import AddonSemanticInspectionResult from './AddonSemanticInspectionResult';
import AddonSemanticNewFaceVerificationResult from './AddonSemanticNewFaceVerificationResult';
import AddonSemanticOnlineReservationCapability from './AddonSemanticOnlineReservationCapability';
import AddonSemanticOwnershipResult from './AddonSemanticOwnershipResult';
import AddonSemanticPostVerificationResult from './AddonSemanticPostVerificationResult';
import AddonsAddonSemanticPaymentMethod from './AddonsAddonSemanticPaymentMethod';
import AddonsAddonSemanticStatus from './AddonsAddonSemanticStatus';

/**
 * The AddonsAddonSemantic model module.
 * @module model/AddonsAddonSemantic
 * @version 0.1.0
 */
class AddonsAddonSemantic {
    /**
     * Constructs a new <code>AddonsAddonSemantic</code>.
     * پیام استخراج‌شده توسط OpenPlatform از semantic ارائه‌دهنده سرویس. راهنما: - قبل از افزودن enum جدید، بررسی کنید که آیا مقدار مناسبی وجود دارد. - مقدار صفر هر enum باید {ENUM_NAME}_UNSPECIFIED باشد. - مقادیر Enum نباید مختص آگهی یا شخص خاصی باشند.
     * @alias module:model/AddonsAddonSemantic
     */
    constructor() { 
        
        AddonsAddonSemantic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddonsAddonSemantic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddonsAddonSemantic} obj Optional instance to populate.
     * @return {module:model/AddonsAddonSemantic} The populated <code>AddonsAddonSemantic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddonsAddonSemantic();

            if (data.hasOwnProperty('car_verification_failure_reason')) {
                obj['car_verification_failure_reason'] = AddonSemanticCarVerificationStage.constructFromObject(data['car_verification_failure_reason']);
            }
            if (data.hasOwnProperty('car_verification_last_successful_stage')) {
                obj['car_verification_last_successful_stage'] = AddonSemanticCarVerificationStage.constructFromObject(data['car_verification_last_successful_stage']);
            }
            if (data.hasOwnProperty('identity_verification_failure_reason')) {
                obj['identity_verification_failure_reason'] = AddonSemanticIdentityVerificationStage.constructFromObject(data['identity_verification_failure_reason']);
            }
            if (data.hasOwnProperty('identity_verification_last_successful_stage')) {
                obj['identity_verification_last_successful_stage'] = AddonSemanticIdentityVerificationStage.constructFromObject(data['identity_verification_last_successful_stage']);
            }
            if (data.hasOwnProperty('identity_verification_result')) {
                obj['identity_verification_result'] = AddonSemanticIdentityVerificationResult.constructFromObject(data['identity_verification_result']);
            }
            if (data.hasOwnProperty('inspection_result')) {
                obj['inspection_result'] = AddonSemanticInspectionResult.constructFromObject(data['inspection_result']);
            }
            if (data.hasOwnProperty('new_face_verification_result')) {
                obj['new_face_verification_result'] = AddonSemanticNewFaceVerificationResult.constructFromObject(data['new_face_verification_result']);
            }
            if (data.hasOwnProperty('online_reservation_capability')) {
                obj['online_reservation_capability'] = AddonSemanticOnlineReservationCapability.constructFromObject(data['online_reservation_capability']);
            }
            if (data.hasOwnProperty('ownership_result')) {
                obj['ownership_result'] = AddonSemanticOwnershipResult.constructFromObject(data['ownership_result']);
            }
            if (data.hasOwnProperty('payment_method')) {
                obj['payment_method'] = AddonsAddonSemanticPaymentMethod.constructFromObject(data['payment_method']);
            }
            if (data.hasOwnProperty('post_verification_result')) {
                obj['post_verification_result'] = AddonSemanticPostVerificationResult.constructFromObject(data['post_verification_result']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = AddonsAddonSemanticStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddonsAddonSemantic</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddonsAddonSemantic</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * @return {module:model/AddonSemanticCarVerificationStage}
     */
    getCarVerificationFailureReason() {
        return this.car_verification_failure_reason;
    }

    /**
     * @param {module:model/AddonSemanticCarVerificationStage} carVerificationFailureReason
     */
    setCarVerificationFailureReason(carVerificationFailureReason) {
        this['car_verification_failure_reason'] = carVerificationFailureReason;
    }
/**
     * @return {module:model/AddonSemanticCarVerificationStage}
     */
    getCarVerificationLastSuccessfulStage() {
        return this.car_verification_last_successful_stage;
    }

    /**
     * @param {module:model/AddonSemanticCarVerificationStage} carVerificationLastSuccessfulStage
     */
    setCarVerificationLastSuccessfulStage(carVerificationLastSuccessfulStage) {
        this['car_verification_last_successful_stage'] = carVerificationLastSuccessfulStage;
    }
/**
     * @return {module:model/AddonSemanticIdentityVerificationStage}
     */
    getIdentityVerificationFailureReason() {
        return this.identity_verification_failure_reason;
    }

    /**
     * @param {module:model/AddonSemanticIdentityVerificationStage} identityVerificationFailureReason
     */
    setIdentityVerificationFailureReason(identityVerificationFailureReason) {
        this['identity_verification_failure_reason'] = identityVerificationFailureReason;
    }
/**
     * @return {module:model/AddonSemanticIdentityVerificationStage}
     */
    getIdentityVerificationLastSuccessfulStage() {
        return this.identity_verification_last_successful_stage;
    }

    /**
     * @param {module:model/AddonSemanticIdentityVerificationStage} identityVerificationLastSuccessfulStage
     */
    setIdentityVerificationLastSuccessfulStage(identityVerificationLastSuccessfulStage) {
        this['identity_verification_last_successful_stage'] = identityVerificationLastSuccessfulStage;
    }
/**
     * @return {module:model/AddonSemanticIdentityVerificationResult}
     */
    getIdentityVerificationResult() {
        return this.identity_verification_result;
    }

    /**
     * @param {module:model/AddonSemanticIdentityVerificationResult} identityVerificationResult
     */
    setIdentityVerificationResult(identityVerificationResult) {
        this['identity_verification_result'] = identityVerificationResult;
    }
/**
     * @return {module:model/AddonSemanticInspectionResult}
     */
    getInspectionResult() {
        return this.inspection_result;
    }

    /**
     * @param {module:model/AddonSemanticInspectionResult} inspectionResult
     */
    setInspectionResult(inspectionResult) {
        this['inspection_result'] = inspectionResult;
    }
/**
     * @return {module:model/AddonSemanticNewFaceVerificationResult}
     */
    getNewFaceVerificationResult() {
        return this.new_face_verification_result;
    }

    /**
     * @param {module:model/AddonSemanticNewFaceVerificationResult} newFaceVerificationResult
     */
    setNewFaceVerificationResult(newFaceVerificationResult) {
        this['new_face_verification_result'] = newFaceVerificationResult;
    }
/**
     * @return {module:model/AddonSemanticOnlineReservationCapability}
     */
    getOnlineReservationCapability() {
        return this.online_reservation_capability;
    }

    /**
     * @param {module:model/AddonSemanticOnlineReservationCapability} onlineReservationCapability
     */
    setOnlineReservationCapability(onlineReservationCapability) {
        this['online_reservation_capability'] = onlineReservationCapability;
    }
/**
     * @return {module:model/AddonSemanticOwnershipResult}
     */
    getOwnershipResult() {
        return this.ownership_result;
    }

    /**
     * @param {module:model/AddonSemanticOwnershipResult} ownershipResult
     */
    setOwnershipResult(ownershipResult) {
        this['ownership_result'] = ownershipResult;
    }
/**
     * @return {module:model/AddonsAddonSemanticPaymentMethod}
     */
    getPaymentMethod() {
        return this.payment_method;
    }

    /**
     * @param {module:model/AddonsAddonSemanticPaymentMethod} paymentMethod
     */
    setPaymentMethod(paymentMethod) {
        this['payment_method'] = paymentMethod;
    }
/**
     * @return {module:model/AddonSemanticPostVerificationResult}
     */
    getPostVerificationResult() {
        return this.post_verification_result;
    }

    /**
     * @param {module:model/AddonSemanticPostVerificationResult} postVerificationResult
     */
    setPostVerificationResult(postVerificationResult) {
        this['post_verification_result'] = postVerificationResult;
    }
/**
     * @return {module:model/AddonsAddonSemanticStatus}
     */
    getStatus() {
        return this.status;
    }

    /**
     * @param {module:model/AddonsAddonSemanticStatus} status
     */
    setStatus(status) {
        this['status'] = status;
    }

}



/**
 * @member {module:model/AddonSemanticCarVerificationStage} car_verification_failure_reason
 */
AddonsAddonSemantic.prototype['car_verification_failure_reason'] = undefined;

/**
 * @member {module:model/AddonSemanticCarVerificationStage} car_verification_last_successful_stage
 */
AddonsAddonSemantic.prototype['car_verification_last_successful_stage'] = undefined;

/**
 * @member {module:model/AddonSemanticIdentityVerificationStage} identity_verification_failure_reason
 */
AddonsAddonSemantic.prototype['identity_verification_failure_reason'] = undefined;

/**
 * @member {module:model/AddonSemanticIdentityVerificationStage} identity_verification_last_successful_stage
 */
AddonsAddonSemantic.prototype['identity_verification_last_successful_stage'] = undefined;

/**
 * @member {module:model/AddonSemanticIdentityVerificationResult} identity_verification_result
 */
AddonsAddonSemantic.prototype['identity_verification_result'] = undefined;

/**
 * @member {module:model/AddonSemanticInspectionResult} inspection_result
 */
AddonsAddonSemantic.prototype['inspection_result'] = undefined;

/**
 * @member {module:model/AddonSemanticNewFaceVerificationResult} new_face_verification_result
 */
AddonsAddonSemantic.prototype['new_face_verification_result'] = undefined;

/**
 * @member {module:model/AddonSemanticOnlineReservationCapability} online_reservation_capability
 */
AddonsAddonSemantic.prototype['online_reservation_capability'] = undefined;

/**
 * @member {module:model/AddonSemanticOwnershipResult} ownership_result
 */
AddonsAddonSemantic.prototype['ownership_result'] = undefined;

/**
 * @member {module:model/AddonsAddonSemanticPaymentMethod} payment_method
 */
AddonsAddonSemantic.prototype['payment_method'] = undefined;

/**
 * @member {module:model/AddonSemanticPostVerificationResult} post_verification_result
 */
AddonsAddonSemantic.prototype['post_verification_result'] = undefined;

/**
 * @member {module:model/AddonsAddonSemanticStatus} status
 */
AddonsAddonSemantic.prototype['status'] = undefined;






export default AddonsAddonSemantic;

