/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AddonsAddonSemanticStatus.
* @enum {}
* @readonly
*/
export default class AddonsAddonSemanticStatus {
    
        /**
         * value: "SUCCEEDED"
         * @const
         */
        "SUCCEEDED" = "SUCCEEDED";

    
        /**
         * value: "FAILED"
         * @const
         */
        "FAILED" = "FAILED";

    
        /**
         * value: "EXPIRED"
         * @const
         */
        "EXPIRED" = "EXPIRED";

    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    

    /**
    * Returns a <code>AddonsAddonSemanticStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AddonsAddonSemanticStatus} The enum <code>AddonsAddonSemanticStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

