/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddonsOpenPostManagePage model module.
 * @module model/AddonsOpenPostManagePage
 * @version 0.1.0
 */
class AddonsOpenPostManagePage {
    /**
     * Constructs a new <code>AddonsOpenPostManagePage</code>.
     * An action to open a post management page in the app
     * @alias module:model/AddonsOpenPostManagePage
     * @param postToken {String} Token of the post to redirect to its management page
     */
    constructor(postToken) { 
        
        AddonsOpenPostManagePage.initialize(this, postToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, postToken) { 
        obj['post_token'] = postToken;
    }

    /**
     * Constructs a <code>AddonsOpenPostManagePage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddonsOpenPostManagePage} obj Optional instance to populate.
     * @return {module:model/AddonsOpenPostManagePage} The populated <code>AddonsOpenPostManagePage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddonsOpenPostManagePage();

            if (data.hasOwnProperty('post_token')) {
                obj['post_token'] = ApiClient.convertToType(data['post_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddonsOpenPostManagePage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddonsOpenPostManagePage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddonsOpenPostManagePage.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['post_token'] && !(typeof data['post_token'] === 'string' || data['post_token'] instanceof String)) {
            throw new Error("Expected the field `post_token` to be a primitive type in the JSON string but got " + data['post_token']);
        }

        return true;
    }

/**
     * Returns Token of the post to redirect to its management page
     * @return {String}
     */
    getPostToken() {
        return this.post_token;
    }

    /**
     * Sets Token of the post to redirect to its management page
     * @param {String} postToken Token of the post to redirect to its management page
     */
    setPostToken(postToken) {
        this['post_token'] = postToken;
    }

}

AddonsOpenPostManagePage.RequiredProperties = ["post_token"];

/**
 * Token of the post to redirect to its management page
 * @member {String} post_token
 */
AddonsOpenPostManagePage.prototype['post_token'] = undefined;






export default AddonsOpenPostManagePage;

