/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AppsAppStatusStatus.
* @enum {}
* @readonly
*/
export default class AppsAppStatusStatus {
    
        /**
         * value: "ACTIVE"
         * @const
         */
        "ACTIVE" = "ACTIVE";

    
        /**
         * value: "INACTIVE"
         * @const
         */
        "INACTIVE" = "INACTIVE";

    
        /**
         * value: "SUSPENDED"
         * @const
         */
        "SUSPENDED" = "SUSPENDED";

    
        /**
         * value: "DEVELOPMENT"
         * @const
         */
        "DEVELOPMENT" = "DEVELOPMENT";

    

    /**
    * Returns a <code>AppsAppStatusStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AppsAppStatusStatus} The enum <code>AppsAppStatusStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

