/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetsGetPermissionsResponseLifeCycleState from './AssetsGetPermissionsResponseLifeCycleState';

/**
 * The AssetsGetPermissionsResponsePermission model module.
 * @module model/AssetsGetPermissionsResponsePermission
 * @version 0.1.0
 */
class AssetsGetPermissionsResponsePermission {
    /**
     * Constructs a new <code>AssetsGetPermissionsResponsePermission</code>.
     * @alias module:model/AssetsGetPermissionsResponsePermission
     */
    constructor() { 
        
        AssetsGetPermissionsResponsePermission.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsGetPermissionsResponsePermission</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsGetPermissionsResponsePermission} obj Optional instance to populate.
     * @return {module:model/AssetsGetPermissionsResponsePermission} The populated <code>AssetsGetPermissionsResponsePermission</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsGetPermissionsResponsePermission();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('display')) {
                obj['display'] = ApiClient.convertToType(data['display'], 'String');
            }
            if (data.hasOwnProperty('lifecycle_state')) {
                obj['lifecycle_state'] = AssetsGetPermissionsResponseLifeCycleState.constructFromObject(data['lifecycle_state']);
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsGetPermissionsResponsePermission</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsGetPermissionsResponsePermission</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['display'] && !(typeof data['display'] === 'string' || data['display'] instanceof String)) {
            throw new Error("Expected the field `display` to be a primitive type in the JSON string but got " + data['display']);
        }
        // ensure the json data is a string
        if (data['slug'] && !(typeof data['slug'] === 'string' || data['slug'] instanceof String)) {
            throw new Error("Expected the field `slug` to be a primitive type in the JSON string but got " + data['slug']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {String}
     */
    getDisplay() {
        return this.display;
    }

    /**
     * @param {String} display
     */
    setDisplay(display) {
        this['display'] = display;
    }
/**
     * @return {module:model/AssetsGetPermissionsResponseLifeCycleState}
     */
    getLifecycleState() {
        return this.lifecycle_state;
    }

    /**
     * @param {module:model/AssetsGetPermissionsResponseLifeCycleState} lifecycleState
     */
    setLifecycleState(lifecycleState) {
        this['lifecycle_state'] = lifecycleState;
    }
/**
     * @return {String}
     */
    getSlug() {
        return this.slug;
    }

    /**
     * @param {String} slug
     */
    setSlug(slug) {
        this['slug'] = slug;
    }

}



/**
 * @member {String} description
 */
AssetsGetPermissionsResponsePermission.prototype['description'] = undefined;

/**
 * @member {String} display
 */
AssetsGetPermissionsResponsePermission.prototype['display'] = undefined;

/**
 * @member {module:model/AssetsGetPermissionsResponseLifeCycleState} lifecycle_state
 */
AssetsGetPermissionsResponsePermission.prototype['lifecycle_state'] = undefined;

/**
 * @member {String} slug
 */
AssetsGetPermissionsResponsePermission.prototype['slug'] = undefined;






export default AssetsGetPermissionsResponsePermission;

