/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetsGetOAuthScopesResponseLifeCycleState from './AssetsGetOAuthScopesResponseLifeCycleState';
import OAuthScopeScope from './OAuthScopeScope';

/**
 * The AssetsGetOAuthScopesResponseAppOauthScope model module.
 * @module model/AssetsGetOAuthScopesResponseAppOauthScope
 * @version 0.1.0
 */
class AssetsGetOAuthScopesResponseAppOauthScope {
    /**
     * Constructs a new <code>AssetsGetOAuthScopesResponseAppOauthScope</code>.
     * @alias module:model/AssetsGetOAuthScopesResponseAppOauthScope
     */
    constructor() { 
        
        AssetsGetOAuthScopesResponseAppOauthScope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsGetOAuthScopesResponseAppOauthScope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsGetOAuthScopesResponseAppOauthScope} obj Optional instance to populate.
     * @return {module:model/AssetsGetOAuthScopesResponseAppOauthScope} The populated <code>AssetsGetOAuthScopesResponseAppOauthScope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsGetOAuthScopesResponseAppOauthScope();

            if (data.hasOwnProperty('slug')) {
                obj['slug'] = OAuthScopeScope.constructFromObject(data['slug']);
            }
            if (data.hasOwnProperty('display')) {
                obj['display'] = ApiClient.convertToType(data['display'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('lifecycle_state')) {
                obj['lifecycle_state'] = AssetsGetOAuthScopesResponseLifeCycleState.constructFromObject(data['lifecycle_state']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsGetOAuthScopesResponseAppOauthScope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsGetOAuthScopesResponseAppOauthScope</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['display'] && !(typeof data['display'] === 'string' || data['display'] instanceof String)) {
            throw new Error("Expected the field `display` to be a primitive type in the JSON string but got " + data['display']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }

/**
     * @return {module:model/OAuthScopeScope}
     */
    getSlug() {
        return this.slug;
    }

    /**
     * @param {module:model/OAuthScopeScope} slug
     */
    setSlug(slug) {
        this['slug'] = slug;
    }
/**
     * @return {String}
     */
    getDisplay() {
        return this.display;
    }

    /**
     * @param {String} display
     */
    setDisplay(display) {
        this['display'] = display;
    }
/**
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * @param {String} description
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * @return {module:model/AssetsGetOAuthScopesResponseLifeCycleState}
     */
    getLifecycleState() {
        return this.lifecycle_state;
    }

    /**
     * @param {module:model/AssetsGetOAuthScopesResponseLifeCycleState} lifecycleState
     */
    setLifecycleState(lifecycleState) {
        this['lifecycle_state'] = lifecycleState;
    }

}



/**
 * @member {module:model/OAuthScopeScope} slug
 */
AssetsGetOAuthScopesResponseAppOauthScope.prototype['slug'] = undefined;

/**
 * @member {String} display
 */
AssetsGetOAuthScopesResponseAppOauthScope.prototype['display'] = undefined;

/**
 * @member {String} description
 */
AssetsGetOAuthScopesResponseAppOauthScope.prototype['description'] = undefined;

/**
 * @member {module:model/AssetsGetOAuthScopesResponseLifeCycleState} lifecycle_state
 */
AssetsGetOAuthScopesResponseAppOauthScope.prototype['lifecycle_state'] = undefined;






export default AssetsGetOAuthScopesResponseAppOauthScope;

