/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AssetsGetOAuthScopesResponseLifeCycleState.
* @enum {}
* @readonly
*/
export default class AssetsGetOAuthScopesResponseLifeCycleState {
    
        /**
         * value: "EXPERIMENTAL"
         * @const
         */
        "EXPERIMENTAL" = "EXPERIMENTAL";

    
        /**
         * value: "ACTIVE"
         * @const
         */
        "ACTIVE" = "ACTIVE";

    
        /**
         * value: "DEPRECATING_SOON"
         * @const
         */
        "DEPRECATING_SOON" = "DEPRECATING_SOON";

    
        /**
         * value: "DEPRECATED"
         * @const
         */
        "DEPRECATED" = "DEPRECATED";

    

    /**
    * Returns a <code>AssetsGetOAuthScopesResponseLifeCycleState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AssetsGetOAuthScopesResponseLifeCycleState} The enum <code>AssetsGetOAuthScopesResponseLifeCycleState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

