/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetServiceTypesResponseServiceTypeData from './GetServiceTypesResponseServiceTypeData';

/**
 * The AssetsGetServiceTypesResponse model module.
 * @module model/AssetsGetServiceTypesResponse
 * @version version not set
 */
class AssetsGetServiceTypesResponse {
    /**
     * Constructs a new <code>AssetsGetServiceTypesResponse</code>.
     * @alias module:model/AssetsGetServiceTypesResponse
     */
    constructor() { 
        
        AssetsGetServiceTypesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsGetServiceTypesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsGetServiceTypesResponse} obj Optional instance to populate.
     * @return {module:model/AssetsGetServiceTypesResponse} The populated <code>AssetsGetServiceTypesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsGetServiceTypesResponse();

            if (data.hasOwnProperty('service_types')) {
                obj['service_types'] = ApiClient.convertToType(data['service_types'], [GetServiceTypesResponseServiceTypeData]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsGetServiceTypesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsGetServiceTypesResponse</code>.
     */
    static validateJSON(data) {
        if (data['service_types']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['service_types'])) {
                throw new Error("Expected the field `service_types` to be an array in the JSON data but got " + data['service_types']);
            }
            // validate the optional field `service_types` (array)
            for (const item of data['service_types']) {
                GetServiceTypesResponseServiceTypeData.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/GetServiceTypesResponseServiceTypeData>} service_types
 */
AssetsGetServiceTypesResponse.prototype['service_types'] = undefined;






export default AssetsGetServiceTypesResponse;

