/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetsGetSubmitSchemaResponse model module.
 * @module model/AssetsGetSubmitSchemaResponse
 * @version 0.1.0
 */
class AssetsGetSubmitSchemaResponse {
    /**
     * Constructs a new <code>AssetsGetSubmitSchemaResponse</code>.
     * @alias module:model/AssetsGetSubmitSchemaResponse
     */
    constructor() { 
        
        AssetsGetSubmitSchemaResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsGetSubmitSchemaResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsGetSubmitSchemaResponse} obj Optional instance to populate.
     * @return {module:model/AssetsGetSubmitSchemaResponse} The populated <code>AssetsGetSubmitSchemaResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsGetSubmitSchemaResponse();

            if (data.hasOwnProperty('schema')) {
                obj['schema'] = ApiClient.convertToType(data['schema'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsGetSubmitSchemaResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsGetSubmitSchemaResponse</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * @return {Object}
     */
    getSchema() {
        return this.schema;
    }

    /**
     * @param {Object} schema
     */
    setSchema(schema) {
        this['schema'] = schema;
    }

}



/**
 * @member {Object} schema
 */
AssetsGetSubmitSchemaResponse.prototype['schema'] = undefined;






export default AssetsGetSubmitSchemaResponse;

