/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AssetsGetPermissionsResponsePermission from './AssetsGetPermissionsResponsePermission';

/**
 * The AssetsGetPermissionsResponse model module.
 * @module model/AssetsGetPermissionsResponse
 * @version 0.1.0
 */
class AssetsGetPermissionsResponse {
    /**
     * Constructs a new <code>AssetsGetPermissionsResponse</code>.
     * @alias module:model/AssetsGetPermissionsResponse
     */
    constructor() { 
        
        AssetsGetPermissionsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsGetPermissionsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsGetPermissionsResponse} obj Optional instance to populate.
     * @return {module:model/AssetsGetPermissionsResponse} The populated <code>AssetsGetPermissionsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsGetPermissionsResponse();

            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], [AssetsGetPermissionsResponsePermission]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsGetPermissionsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsGetPermissionsResponse</code>.
     */
    static validateJSON(data) {
        if (data['permissions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['permissions'])) {
                throw new Error("Expected the field `permissions` to be an array in the JSON data but got " + data['permissions']);
            }
            // validate the optional field `permissions` (array)
            for (const item of data['permissions']) {
                AssetsGetPermissionsResponsePermission.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/AssetsGetPermissionsResponsePermission>}
     */
    getPermissions() {
        return this.permissions;
    }

    /**
     * @param {Array.<module:model/AssetsGetPermissionsResponsePermission>} permissions
     */
    setPermissions(permissions) {
        this['permissions'] = permissions;
    }

}



/**
 * @member {Array.<module:model/AssetsGetPermissionsResponsePermission>} permissions
 */
AssetsGetPermissionsResponse.prototype['permissions'] = undefined;






export default AssetsGetPermissionsResponse;

