/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BaseBusinessType.
* @enum {}
* @readonly
*/
export default class BaseBusinessType {
    
        /**
         * value: "REAL_ESTATE_BUSINESS"
         * @const
         */
        "REAL_ESTATE_BUSINESS" = "REAL_ESTATE_BUSINESS";

    
        /**
         * value: "CAR_BUSINESS"
         * @const
         */
        "CAR_BUSINESS" = "CAR_BUSINESS";

    
        /**
         * value: "MARKETPLACE_BUSINESS"
         * @const
         */
        "MARKETPLACE_BUSINESS" = "MARKETPLACE_BUSINESS";

    
        /**
         * value: "CAR_CONCIERGE_SALE"
         * @const
         */
        "CAR_CONCIERGE_SALE" = "CAR_CONCIERGE_SALE";

    
        /**
         * value: "PERSONAL"
         * @const
         */
        "PERSONAL" = "PERSONAL";

    
        /**
         * value: "JOBS_BUSINESS"
         * @const
         */
        "JOBS_BUSINESS" = "JOBS_BUSINESS";

    
        /**
         * value: "PREMIUM_PANEL"
         * @const
         */
        "PREMIUM_PANEL" = "PREMIUM_PANEL";

    

    /**
    * Returns a <code>BaseBusinessType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BaseBusinessType} The enum <code>BaseBusinessType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

