/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChatapiChatButtonRow from './ChatapiChatButtonRow';

/**
 * The ChatapiChatButtonGrid model module.
 * @module model/ChatapiChatButtonGrid
 * @version 0.1.0
 */
class ChatapiChatButtonGrid {
    /**
     * Constructs a new <code>ChatapiChatButtonGrid</code>.
     * @alias module:model/ChatapiChatButtonGrid
     */
    constructor() { 
        
        ChatapiChatButtonGrid.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChatapiChatButtonGrid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChatapiChatButtonGrid} obj Optional instance to populate.
     * @return {module:model/ChatapiChatButtonGrid} The populated <code>ChatapiChatButtonGrid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChatapiChatButtonGrid();

            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], [ChatapiChatButtonRow]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChatapiChatButtonGrid</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChatapiChatButtonGrid</code>.
     */
    static validateJSON(data) {
        if (data['rows']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['rows'])) {
                throw new Error("Expected the field `rows` to be an array in the JSON data but got " + data['rows']);
            }
            // validate the optional field `rows` (array)
            for (const item of data['rows']) {
                ChatapiChatButtonRow.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/ChatapiChatButtonRow>}
     */
    getRows() {
        return this.rows;
    }

    /**
     * @param {Array.<module:model/ChatapiChatButtonRow>} rows
     */
    setRows(rows) {
        this['rows'] = rows;
    }

}



/**
 * @member {Array.<module:model/ChatapiChatButtonRow>} rows
 */
ChatapiChatButtonGrid.prototype['rows'] = undefined;






export default ChatapiChatButtonGrid;

