/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DarvazeRequestCarOwnershipDelegationResponse model module.
 * @module model/DarvazeRequestCarOwnershipDelegationResponse
 * @version 0.1.0
 */
class DarvazeRequestCarOwnershipDelegationResponse {
    /**
     * Constructs a new <code>DarvazeRequestCarOwnershipDelegationResponse</code>.
     * @alias module:model/DarvazeRequestCarOwnershipDelegationResponse
     */
    constructor() { 
        
        DarvazeRequestCarOwnershipDelegationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DarvazeRequestCarOwnershipDelegationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DarvazeRequestCarOwnershipDelegationResponse} obj Optional instance to populate.
     * @return {module:model/DarvazeRequestCarOwnershipDelegationResponse} The populated <code>DarvazeRequestCarOwnershipDelegationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DarvazeRequestCarOwnershipDelegationResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DarvazeRequestCarOwnershipDelegationResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DarvazeRequestCarOwnershipDelegationResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * @param {String} id
     */
    setId(id) {
        this['id'] = id;
    }

}



/**
 * @member {String} id
 */
DarvazeRequestCarOwnershipDelegationResponse.prototype['id'] = undefined;






export default DarvazeRequestCarOwnershipDelegationResponse;

