/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class FinderPostExtState.
* @enum {}
* @readonly
*/
export default class FinderPostExtState {
    
        /**
         * value: "PUBLISHED"
         * @const
         */
        "PUBLISHED" = "PUBLISHED";

    
        /**
         * value: "REVIEW_REQ"
         * @const
         */
        "REVIEW_REQ" = "REVIEW_REQ";

    
        /**
         * value: "PAYMENT_REQ"
         * @const
         */
        "PAYMENT_REQ" = "PAYMENT_REQ";

    
        /**
         * value: "RETIRED"
         * @const
         */
        "RETIRED" = "RETIRED";

    

    /**
    * Returns a <code>FinderPostExtState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/FinderPostExtState} The enum <code>FinderPostExtState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

