/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ManagementDevelopmentPost from './ManagementDevelopmentPost';

/**
 * The FinderGetAllDevelopmentPostsResponse model module.
 * @module model/FinderGetAllDevelopmentPostsResponse
 * @version 0.1.0
 */
class FinderGetAllDevelopmentPostsResponse {
    /**
     * Constructs a new <code>FinderGetAllDevelopmentPostsResponse</code>.
     * @alias module:model/FinderGetAllDevelopmentPostsResponse
     */
    constructor() { 
        
        FinderGetAllDevelopmentPostsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinderGetAllDevelopmentPostsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinderGetAllDevelopmentPostsResponse} obj Optional instance to populate.
     * @return {module:model/FinderGetAllDevelopmentPostsResponse} The populated <code>FinderGetAllDevelopmentPostsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinderGetAllDevelopmentPostsResponse();

            if (data.hasOwnProperty('development_posts')) {
                obj['development_posts'] = ApiClient.convertToType(data['development_posts'], [ManagementDevelopmentPost]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FinderGetAllDevelopmentPostsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FinderGetAllDevelopmentPostsResponse</code>.
     */
    static validateJSON(data) {
        if (data['development_posts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['development_posts'])) {
                throw new Error("Expected the field `development_posts` to be an array in the JSON data but got " + data['development_posts']);
            }
            // validate the optional field `development_posts` (array)
            for (const item of data['development_posts']) {
                ManagementDevelopmentPost.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/ManagementDevelopmentPost>}
     */
    getDevelopmentPosts() {
        return this.development_posts;
    }

    /**
     * @param {Array.<module:model/ManagementDevelopmentPost>} developmentPosts
     */
    setDevelopmentPosts(developmentPosts) {
        this['development_posts'] = developmentPosts;
    }

}



/**
 * @member {Array.<module:model/ManagementDevelopmentPost>} development_posts
 */
FinderGetAllDevelopmentPostsResponse.prototype['development_posts'] = undefined;






export default FinderGetAllDevelopmentPostsResponse;

