/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PremiumPanelBusinessDataSubBusinessType from './PremiumPanelBusinessDataSubBusinessType';

/**
 * The GetPostResponseBusinessData model module.
 * @module model/GetPostResponseBusinessData
 * @version version not set
 */
class GetPostResponseBusinessData {
    /**
     * Constructs a new <code>GetPostResponseBusinessData</code>.
     * @alias module:model/GetPostResponseBusinessData
     */
    constructor() { 
        
        GetPostResponseBusinessData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPostResponseBusinessData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPostResponseBusinessData} obj Optional instance to populate.
     * @return {module:model/GetPostResponseBusinessData} The populated <code>GetPostResponseBusinessData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPostResponseBusinessData();

            if (data.hasOwnProperty('business_type')) {
                obj['business_type'] = PremiumPanelBusinessDataSubBusinessType.constructFromObject(data['business_type']);
            }
            if (data.hasOwnProperty('business_name')) {
                obj['business_name'] = ApiClient.convertToType(data['business_name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPostResponseBusinessData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPostResponseBusinessData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['business_name'] && !(typeof data['business_name'] === 'string' || data['business_name'] instanceof String)) {
            throw new Error("Expected the field `business_name` to be a primitive type in the JSON string but got " + data['business_name']);
        }

        return true;
    }


}



/**
 * @member {module:model/PremiumPanelBusinessDataSubBusinessType} business_type
 */
GetPostResponseBusinessData.prototype['business_type'] = undefined;

/**
 * @member {String} business_name
 */
GetPostResponseBusinessData.prototype['business_name'] = undefined;






export default GetPostResponseBusinessData;

