/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetPostStatsResponseDailyStats from './GetPostStatsResponseDailyStats';

/**
 * The GetPostStatsResponsePostStats model module.
 * @module model/GetPostStatsResponsePostStats
 * @version 0.1.0
 */
class GetPostStatsResponsePostStats {
    /**
     * Constructs a new <code>GetPostStatsResponsePostStats</code>.
     * @alias module:model/GetPostStatsResponsePostStats
     */
    constructor() { 
        
        GetPostStatsResponsePostStats.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPostStatsResponsePostStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPostStatsResponsePostStats} obj Optional instance to populate.
     * @return {module:model/GetPostStatsResponsePostStats} The populated <code>GetPostStatsResponsePostStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPostStatsResponsePostStats();

            if (data.hasOwnProperty('daily')) {
                obj['daily'] = ApiClient.convertToType(data['daily'], [GetPostStatsResponseDailyStats]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetPostStatsResponsePostStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetPostStatsResponsePostStats</code>.
     */
    static validateJSON(data) {
        if (data['daily']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['daily'])) {
                throw new Error("Expected the field `daily` to be an array in the JSON data but got " + data['daily']);
            }
            // validate the optional field `daily` (array)
            for (const item of data['daily']) {
                GetPostStatsResponseDailyStats.validateJSON(item);
            };
        }

        return true;
    }

/**
     * @return {Array.<module:model/GetPostStatsResponseDailyStats>}
     */
    getDaily() {
        return this.daily;
    }

    /**
     * @param {Array.<module:model/GetPostStatsResponseDailyStats>} daily
     */
    setDaily(daily) {
        this['daily'] = daily;
    }
/**
     * @return {Number}
     */
    getTotal() {
        return this.total;
    }

    /**
     * @param {Number} total
     */
    setTotal(total) {
        this['total'] = total;
    }

}



/**
 * @member {Array.<module:model/GetPostStatsResponseDailyStats>} daily
 */
GetPostStatsResponsePostStats.prototype['daily'] = undefined;

/**
 * @member {Number} total
 */
GetPostStatsResponsePostStats.prototype['total'] = undefined;






export default GetPostStatsResponsePostStats;

