/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HomePresellFieldsDeliveryYear.
* @enum {}
* @readonly
*/
export default class HomePresellFieldsDeliveryYear {
    
        /**
         * value: "DELIVERY_YEAR_1404"
         * @const
         */
        "DELIVERY_YEAR_1404" = "DELIVERY_YEAR_1404";

    
        /**
         * value: "DELIVERY_YEAR_1405"
         * @const
         */
        "DELIVERY_YEAR_1405" = "DELIVERY_YEAR_1405";

    
        /**
         * value: "DELIVERY_YEAR_1406"
         * @const
         */
        "DELIVERY_YEAR_1406" = "DELIVERY_YEAR_1406";

    
        /**
         * value: "DELIVERY_YEAR_1407"
         * @const
         */
        "DELIVERY_YEAR_1407" = "DELIVERY_YEAR_1407";

    
        /**
         * value: "DELIVERY_YEAR_1408"
         * @const
         */
        "DELIVERY_YEAR_1408" = "DELIVERY_YEAR_1408";

    
        /**
         * value: "DELIVERY_YEAR_1409"
         * @const
         */
        "DELIVERY_YEAR_1409" = "DELIVERY_YEAR_1409";

    
        /**
         * value: "DELIVERY_YEAR_1410"
         * @const
         */
        "DELIVERY_YEAR_1410" = "DELIVERY_YEAR_1410";

    
        /**
         * value: "DELIVERY_YEAR_1411"
         * @const
         */
        "DELIVERY_YEAR_1411" = "DELIVERY_YEAR_1411";

    
        /**
         * value: "DELIVERY_YEAR_1412"
         * @const
         */
        "DELIVERY_YEAR_1412" = "DELIVERY_YEAR_1412";

    
        /**
         * value: "DELIVERY_YEAR_1413"
         * @const
         */
        "DELIVERY_YEAR_1413" = "DELIVERY_YEAR_1413";

    
        /**
         * value: "DELIVERY_YEAR_1414"
         * @const
         */
        "DELIVERY_YEAR_1414" = "DELIVERY_YEAR_1414";

    

    /**
    * Returns a <code>HomePresellFieldsDeliveryYear</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HomePresellFieldsDeliveryYear} The enum <code>HomePresellFieldsDeliveryYear</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

