/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class HomePresellFieldsDeliveryMonth.
* @enum {}
* @readonly
*/
export default class HomePresellFieldsDeliveryMonth {
    
        /**
         * value: "DELIVERY_MONTH_FARVARDIN"
         * @const
         */
        "DELIVERY_MONTH_FARVARDIN" = "DELIVERY_MONTH_FARVARDIN";

    
        /**
         * value: "DELIVERY_MONTH_ORDIBEHESHT"
         * @const
         */
        "DELIVERY_MONTH_ORDIBEHESHT" = "DELIVERY_MONTH_ORDIBEHESHT";

    
        /**
         * value: "DELIVERY_MONTH_KHORDAD"
         * @const
         */
        "DELIVERY_MONTH_KHORDAD" = "DELIVERY_MONTH_KHORDAD";

    
        /**
         * value: "DELIVERY_MONTH_TIR"
         * @const
         */
        "DELIVERY_MONTH_TIR" = "DELIVERY_MONTH_TIR";

    
        /**
         * value: "DELIVERY_MONTH_MORDAD"
         * @const
         */
        "DELIVERY_MONTH_MORDAD" = "DELIVERY_MONTH_MORDAD";

    
        /**
         * value: "DELIVERY_MONTH_SHAHRIVAR"
         * @const
         */
        "DELIVERY_MONTH_SHAHRIVAR" = "DELIVERY_MONTH_SHAHRIVAR";

    
        /**
         * value: "DELIVERY_MONTH_MEHR"
         * @const
         */
        "DELIVERY_MONTH_MEHR" = "DELIVERY_MONTH_MEHR";

    
        /**
         * value: "DELIVERY_MONTH_ABAN"
         * @const
         */
        "DELIVERY_MONTH_ABAN" = "DELIVERY_MONTH_ABAN";

    
        /**
         * value: "DELIVERY_MONTH_AZAR"
         * @const
         */
        "DELIVERY_MONTH_AZAR" = "DELIVERY_MONTH_AZAR";

    
        /**
         * value: "DELIVERY_MONTH_DEY"
         * @const
         */
        "DELIVERY_MONTH_DEY" = "DELIVERY_MONTH_DEY";

    
        /**
         * value: "DELIVERY_MONTH_BAHMAN"
         * @const
         */
        "DELIVERY_MONTH_BAHMAN" = "DELIVERY_MONTH_BAHMAN";

    
        /**
         * value: "DELIVERY_MONTH_ESFAND"
         * @const
         */
        "DELIVERY_MONTH_ESFAND" = "DELIVERY_MONTH_ESFAND";

    

    /**
    * Returns a <code>HomePresellFieldsDeliveryMonth</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/HomePresellFieldsDeliveryMonth} The enum <code>HomePresellFieldsDeliveryMonth</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

