/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageLocationData model module.
 * @module model/MessageLocationData
 * @version 0.1.0
 */
class MessageLocationData {
    /**
     * Constructs a new <code>MessageLocationData</code>.
     * @alias module:model/MessageLocationData
     */
    constructor() { 
        
        MessageLocationData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessageLocationData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageLocationData} obj Optional instance to populate.
     * @return {module:model/MessageLocationData} The populated <code>MessageLocationData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageLocationData();

            if (data.hasOwnProperty('latitude')) {
                obj['latitude'] = ApiClient.convertToType(data['latitude'], 'Number');
            }
            if (data.hasOwnProperty('longitude')) {
                obj['longitude'] = ApiClient.convertToType(data['longitude'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MessageLocationData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MessageLocationData</code>.
     */
    static validateJSON(data) {

        return true;
    }

/**
     * Returns The latitude in degrees. It must be in the range [-90.0, +90.0].
     * @return {Number}
     */
    getLatitude() {
        return this.latitude;
    }

    /**
     * Sets The latitude in degrees. It must be in the range [-90.0, +90.0].
     * @param {Number} latitude The latitude in degrees. It must be in the range [-90.0, +90.0].
     */
    setLatitude(latitude) {
        this['latitude'] = latitude;
    }
/**
     * Returns The longitude in degrees. It must be in the range [-180.0, +180.0].
     * @return {Number}
     */
    getLongitude() {
        return this.longitude;
    }

    /**
     * Sets The longitude in degrees. It must be in the range [-180.0, +180.0].
     * @param {Number} longitude The longitude in degrees. It must be in the range [-180.0, +180.0].
     */
    setLongitude(longitude) {
        this['longitude'] = longitude;
    }

}



/**
 * The latitude in degrees. It must be in the range [-90.0, +90.0].
 * @member {Number} latitude
 */
MessageLocationData.prototype['latitude'] = undefined;

/**
 * The longitude in degrees. It must be in the range [-180.0, +180.0].
 * @member {Number} longitude
 */
MessageLocationData.prototype['longitude'] = undefined;






export default MessageLocationData;

