/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServicesFieldsCategory from './ServicesFieldsCategory';

/**
 * The OpenPlatformpostServicesFields model module.
 * @module model/OpenPlatformpostServicesFields
 * @version 0.1.0
 */
class OpenPlatformpostServicesFields {
    /**
     * Constructs a new <code>OpenPlatformpostServicesFields</code>.
     * @alias module:model/OpenPlatformpostServicesFields
     * @param category {module:model/ServicesFieldsCategory} 
     * @param expertiseIds {Array.<String>} فهرست شناسه‌های تخصص
     * @param workHoursEnd {Number} ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @param workHoursStart {Number} ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @param workOnHolidays {Boolean} آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند
     * @param works247 {Boolean} آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.
     */
    constructor(category, expertiseIds, workHoursEnd, workHoursStart, workOnHolidays, works247) { 
        
        OpenPlatformpostServicesFields.initialize(this, category, expertiseIds, workHoursEnd, workHoursStart, workOnHolidays, works247);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, category, expertiseIds, workHoursEnd, workHoursStart, workOnHolidays, works247) { 
        obj['category'] = category;
        obj['expertise_ids'] = expertiseIds;
        obj['work_hours_end'] = workHoursEnd;
        obj['work_hours_start'] = workHoursStart;
        obj['work_on_holidays'] = workOnHolidays;
        obj['works_24_7'] = works247;
    }

    /**
     * Constructs a <code>OpenPlatformpostServicesFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OpenPlatformpostServicesFields} obj Optional instance to populate.
     * @return {module:model/OpenPlatformpostServicesFields} The populated <code>OpenPlatformpostServicesFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OpenPlatformpostServicesFields();

            if (data.hasOwnProperty('category')) {
                obj['category'] = ServicesFieldsCategory.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('expertise_ids')) {
                obj['expertise_ids'] = ApiClient.convertToType(data['expertise_ids'], ['String']);
            }
            if (data.hasOwnProperty('work_hours_end')) {
                obj['work_hours_end'] = ApiClient.convertToType(data['work_hours_end'], 'Number');
            }
            if (data.hasOwnProperty('work_hours_start')) {
                obj['work_hours_start'] = ApiClient.convertToType(data['work_hours_start'], 'Number');
            }
            if (data.hasOwnProperty('work_on_holidays')) {
                obj['work_on_holidays'] = ApiClient.convertToType(data['work_on_holidays'], 'Boolean');
            }
            if (data.hasOwnProperty('works_24_7')) {
                obj['works_24_7'] = ApiClient.convertToType(data['works_24_7'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OpenPlatformpostServicesFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OpenPlatformpostServicesFields</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OpenPlatformpostServicesFields.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['expertise_ids'])) {
            throw new Error("Expected the field `expertise_ids` to be an array in the JSON data but got " + data['expertise_ids']);
        }

        return true;
    }

/**
     * @return {module:model/ServicesFieldsCategory}
     */
    getCategory() {
        return this.category;
    }

    /**
     * @param {module:model/ServicesFieldsCategory} category
     */
    setCategory(category) {
        this['category'] = category;
    }
/**
     * Returns فهرست شناسه‌های تخصص
     * @return {Array.<String>}
     */
    getExpertiseIds() {
        return this.expertise_ids;
    }

    /**
     * Sets فهرست شناسه‌های تخصص
     * @param {Array.<String>} expertiseIds فهرست شناسه‌های تخصص
     */
    setExpertiseIds(expertiseIds) {
        this['expertise_ids'] = expertiseIds;
    }
/**
     * Returns ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @return {Number}
     */
    getWorkHoursEnd() {
        return this.work_hours_end;
    }

    /**
     * Sets ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @param {Number} workHoursEnd ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     */
    setWorkHoursEnd(workHoursEnd) {
        this['work_hours_end'] = workHoursEnd;
    }
/**
     * Returns ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @return {Number}
     */
    getWorkHoursStart() {
        return this.work_hours_start;
    }

    /**
     * Sets ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     * @param {Number} workHoursStart ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
     */
    setWorkHoursStart(workHoursStart) {
        this['work_hours_start'] = workHoursStart;
    }
/**
     * Returns آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند
     * @return {Boolean}
     */
    getWorkOnHolidays() {
        return this.work_on_holidays;
    }

    /**
     * Sets آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند
     * @param {Boolean} workOnHolidays آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند
     */
    setWorkOnHolidays(workOnHolidays) {
        this['work_on_holidays'] = workOnHolidays;
    }
/**
     * Returns آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.
     * @return {Boolean}
     */
    getWorks247() {
        return this.works_24_7;
    }

    /**
     * Sets آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.
     * @param {Boolean} works247 آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.
     */
    setWorks247(works247) {
        this['works_24_7'] = works247;
    }

}

OpenPlatformpostServicesFields.RequiredProperties = ["category", "expertise_ids", "work_hours_end", "work_hours_start", "work_on_holidays", "works_24_7"];

/**
 * @member {module:model/ServicesFieldsCategory} category
 */
OpenPlatformpostServicesFields.prototype['category'] = undefined;

/**
 * فهرست شناسه‌های تخصص
 * @member {Array.<String>} expertise_ids
 */
OpenPlatformpostServicesFields.prototype['expertise_ids'] = undefined;

/**
 * ساعت پایان کار به فرمت 24 ساعته (مثلاً 18 برای 18:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
 * @member {Number} work_hours_end
 */
OpenPlatformpostServicesFields.prototype['work_hours_end'] = undefined;

/**
 * ساعت شروع کار به فرمت 24 ساعته (مثلاً 9 برای 9:00). فقط در صورتی اعمال می‌شود که `works_24_7` false باشد.
 * @member {Number} work_hours_start
 */
OpenPlatformpostServicesFields.prototype['work_hours_start'] = undefined;

/**
 * آیا ارائه‌دهنده سرویس در تعطیلات کار می‌کند
 * @member {Boolean} work_on_holidays
 */
OpenPlatformpostServicesFields.prototype['work_on_holidays'] = undefined;

/**
 * آیا ارائه‌دهنده سرویس به صورت 24/7 در دسترس است. اگر true باشد، `work_hours_start` و `work_hours_end` نادیده گرفته می‌شوند.
 * @member {Boolean} works_24_7
 */
OpenPlatformpostServicesFields.prototype['works_24_7'] = undefined;






export default OpenPlatformpostServicesFields;

