/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentReorderPostBody model module.
 * @module model/PaymentReorderPostBody
 * @version 0.1.0
 */
class PaymentReorderPostBody {
    /**
     * Constructs a new <code>PaymentReorderPostBody</code>.
     * @alias module:model/PaymentReorderPostBody
     */
    constructor() { 
        
        PaymentReorderPostBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentReorderPostBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentReorderPostBody} obj Optional instance to populate.
     * @return {module:model/PaymentReorderPostBody} The populated <code>PaymentReorderPostBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentReorderPostBody();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('extra_details')) {
                obj['extra_details'] = ApiClient.convertToType(data['extra_details'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentReorderPostBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentReorderPostBody</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['extra_details'] && !(typeof data['extra_details'] === 'string' || data['extra_details'] instanceof String)) {
            throw new Error("Expected the field `extra_details` to be a primitive type in the JSON string but got " + data['extra_details']);
        }

        return true;
    }

/**
     * Returns A Version 4 uuid that must be unique for each payment. This uuid must be generated on your side and sent in the request. If an id is sent that has a successful or semi-successful transaction on the Kenar side, you will receive an error.
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets A Version 4 uuid that must be unique for each payment. This uuid must be generated on your side and sent in the request. If an id is sent that has a successful or semi-successful transaction on the Kenar side, you will receive an error.
     * @param {String} id A Version 4 uuid that must be unique for each payment. This uuid must be generated on your side and sent in the request. If an id is sent that has a successful or semi-successful transaction on the Kenar side, you will receive an error.
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * Returns Additional details that you want to send to the Kenar side. This field is optional and can be used to solve inconsistencies in the transaction.
     * @return {String}
     */
    getExtraDetails() {
        return this.extra_details;
    }

    /**
     * Sets Additional details that you want to send to the Kenar side. This field is optional and can be used to solve inconsistencies in the transaction.
     * @param {String} extraDetails Additional details that you want to send to the Kenar side. This field is optional and can be used to solve inconsistencies in the transaction.
     */
    setExtraDetails(extraDetails) {
        this['extra_details'] = extraDetails;
    }

}



/**
 * A Version 4 uuid that must be unique for each payment. This uuid must be generated on your side and sent in the request. If an id is sent that has a successful or semi-successful transaction on the Kenar side, you will receive an error.
 * @member {String} id
 */
PaymentReorderPostBody.prototype['id'] = undefined;

/**
 * Additional details that you want to send to the Kenar side. This field is optional and can be used to solve inconsistencies in the transaction.
 * @member {String} extra_details
 */
PaymentReorderPostBody.prototype['extra_details'] = undefined;






export default PaymentReorderPostBody;

