/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentReorderPostResponse model module.
 * @module model/PaymentReorderPostResponse
 * @version version not set
 */
class PaymentReorderPostResponse {
    /**
     * Constructs a new <code>PaymentReorderPostResponse</code>.
     * @alias module:model/PaymentReorderPostResponse
     */
    constructor() { 
        
        PaymentReorderPostResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentReorderPostResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentReorderPostResponse} obj Optional instance to populate.
     * @return {module:model/PaymentReorderPostResponse} The populated <code>PaymentReorderPostResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentReorderPostResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('cost_rials')) {
                obj['cost_rials'] = ApiClient.convertToType(data['cost_rials'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentReorderPostResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentReorderPostResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['cost_rials'] && !(typeof data['cost_rials'] === 'string' || data['cost_rials'] instanceof String)) {
            throw new Error("Expected the field `cost_rials` to be a primitive type in the JSON string but got " + data['cost_rials']);
        }

        return true;
    }


}



/**
 * Same uuid when creating transaction
 * @member {String} id
 */
PaymentReorderPostResponse.prototype['id'] = undefined;

/**
 * The cost of the transaction in rials for your application
 * @member {String} cost_rials
 */
PaymentReorderPostResponse.prototype['cost_rials'] = undefined;






export default PaymentReorderPostResponse;

