/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentWalletTransactionStatus from './PaymentWalletTransactionStatus';

/**
 * The PaymentWalletTransaction model module.
 * @module model/PaymentWalletTransaction
 * @version 0.1.0
 */
class PaymentWalletTransaction {
    /**
     * Constructs a new <code>PaymentWalletTransaction</code>.
     * @alias module:model/PaymentWalletTransaction
     */
    constructor() { 
        
        PaymentWalletTransaction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentWalletTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentWalletTransaction} obj Optional instance to populate.
     * @return {module:model/PaymentWalletTransaction} The populated <code>PaymentWalletTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentWalletTransaction();

            if (data.hasOwnProperty('amount_rials')) {
                obj['amount_rials'] = ApiClient.convertToType(data['amount_rials'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentWalletTransactionStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentWalletTransaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentWalletTransaction</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['amount_rials'] && !(typeof data['amount_rials'] === 'string' || data['amount_rials'] instanceof String)) {
            throw new Error("Expected the field `amount_rials` to be a primitive type in the JSON string but got " + data['amount_rials']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getAmountRials() {
        return this.amount_rials;
    }

    /**
     * @param {String} amountRials
     */
    setAmountRials(amountRials) {
        this['amount_rials'] = amountRials;
    }
/**
     * @return {module:model/PaymentWalletTransactionStatus}
     */
    getStatus() {
        return this.status;
    }

    /**
     * @param {module:model/PaymentWalletTransactionStatus} status
     */
    setStatus(status) {
        this['status'] = status;
    }
/**
     * @return {String}
     */
    getToken() {
        return this.token;
    }

    /**
     * @param {String} token
     */
    setToken(token) {
        this['token'] = token;
    }

}



/**
 * @member {String} amount_rials
 */
PaymentWalletTransaction.prototype['amount_rials'] = undefined;

/**
 * @member {module:model/PaymentWalletTransactionStatus} status
 */
PaymentWalletTransaction.prototype['status'] = undefined;

/**
 * @member {String} token
 */
PaymentWalletTransaction.prototype['token'] = undefined;






export default PaymentWalletTransaction;

