/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentCreateWalletPaymentRequest model module.
 * @module model/PaymentCreateWalletPaymentRequest
 * @version 0.1.0
 */
class PaymentCreateWalletPaymentRequest {
    /**
     * Constructs a new <code>PaymentCreateWalletPaymentRequest</code>.
     * @alias module:model/PaymentCreateWalletPaymentRequest
     * @param amountRials {String} Transaction amount in rials
     * @param description {String} A description of the transaction
     * @param redirectUrl {String} The address user should be redirected to after paying the amount
     */
    constructor(amountRials, description, redirectUrl) { 
        
        PaymentCreateWalletPaymentRequest.initialize(this, amountRials, description, redirectUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amountRials, description, redirectUrl) { 
        obj['amount_rials'] = amountRials;
        obj['description'] = description;
        obj['redirect_url'] = redirectUrl;
    }

    /**
     * Constructs a <code>PaymentCreateWalletPaymentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentCreateWalletPaymentRequest} obj Optional instance to populate.
     * @return {module:model/PaymentCreateWalletPaymentRequest} The populated <code>PaymentCreateWalletPaymentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCreateWalletPaymentRequest();

            if (data.hasOwnProperty('amount_rials')) {
                obj['amount_rials'] = ApiClient.convertToType(data['amount_rials'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('redirect_url')) {
                obj['redirect_url'] = ApiClient.convertToType(data['redirect_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentCreateWalletPaymentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentCreateWalletPaymentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentCreateWalletPaymentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['amount_rials'] && !(typeof data['amount_rials'] === 'string' || data['amount_rials'] instanceof String)) {
            throw new Error("Expected the field `amount_rials` to be a primitive type in the JSON string but got " + data['amount_rials']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['redirect_url'] && !(typeof data['redirect_url'] === 'string' || data['redirect_url'] instanceof String)) {
            throw new Error("Expected the field `redirect_url` to be a primitive type in the JSON string but got " + data['redirect_url']);
        }

        return true;
    }

/**
     * Returns Transaction amount in rials
     * @return {String}
     */
    getAmountRials() {
        return this.amount_rials;
    }

    /**
     * Sets Transaction amount in rials
     * @param {String} amountRials Transaction amount in rials
     */
    setAmountRials(amountRials) {
        this['amount_rials'] = amountRials;
    }
/**
     * Returns A description of the transaction
     * @return {String}
     */
    getDescription() {
        return this.description;
    }

    /**
     * Sets A description of the transaction
     * @param {String} description A description of the transaction
     */
    setDescription(description) {
        this['description'] = description;
    }
/**
     * Returns The address user should be redirected to after paying the amount
     * @return {String}
     */
    getRedirectUrl() {
        return this.redirect_url;
    }

    /**
     * Sets The address user should be redirected to after paying the amount
     * @param {String} redirectUrl The address user should be redirected to after paying the amount
     */
    setRedirectUrl(redirectUrl) {
        this['redirect_url'] = redirectUrl;
    }

}

PaymentCreateWalletPaymentRequest.RequiredProperties = ["amount_rials", "description", "redirect_url"];

/**
 * Transaction amount in rials
 * @member {String} amount_rials
 */
PaymentCreateWalletPaymentRequest.prototype['amount_rials'] = undefined;

/**
 * A description of the transaction
 * @member {String} description
 */
PaymentCreateWalletPaymentRequest.prototype['description'] = undefined;

/**
 * The address user should be redirected to after paying the amount
 * @member {String} redirect_url
 */
PaymentCreateWalletPaymentRequest.prototype['redirect_url'] = undefined;






export default PaymentCreateWalletPaymentRequest;

