/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentTransaction from './PaymentTransaction';

/**
 * The PaymentPublishUserPostResponse model module.
 * @module model/PaymentPublishUserPostResponse
 * @version 0.1.0
 */
class PaymentPublishUserPostResponse {
    /**
     * Constructs a new <code>PaymentPublishUserPostResponse</code>.
     * @alias module:model/PaymentPublishUserPostResponse
     */
    constructor() { 
        
        PaymentPublishUserPostResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentPublishUserPostResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentPublishUserPostResponse} obj Optional instance to populate.
     * @return {module:model/PaymentPublishUserPostResponse} The populated <code>PaymentPublishUserPostResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentPublishUserPostResponse();

            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = PaymentTransaction.constructFromObject(data['transaction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentPublishUserPostResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentPublishUserPostResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `transaction`
        if (data['transaction']) { // data not null
          PaymentTransaction.validateJSON(data['transaction']);
        }

        return true;
    }

/**
     * @return {module:model/PaymentTransaction}
     */
    getTransaction() {
        return this.transaction;
    }

    /**
     * @param {module:model/PaymentTransaction} transaction
     */
    setTransaction(transaction) {
        this['transaction'] = transaction;
    }

}



/**
 * @member {module:model/PaymentTransaction} transaction
 */
PaymentPublishUserPostResponse.prototype['transaction'] = undefined;






export default PaymentPublishUserPostResponse;

