/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostCustomizedButton from './PostCustomizedButton';

/**
 * The PostSetPostCustomizedButtonBody model module.
 * @module model/PostSetPostCustomizedButtonBody
 * @version 0.1.0
 */
class PostSetPostCustomizedButtonBody {
    /**
     * Constructs a new <code>PostSetPostCustomizedButtonBody</code>.
     * @alias module:model/PostSetPostCustomizedButtonBody
     * @param customizedButton {module:model/PostCustomizedButton} 
     */
    constructor(customizedButton) { 
        
        PostSetPostCustomizedButtonBody.initialize(this, customizedButton);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, customizedButton) { 
        obj['customized_button'] = customizedButton;
    }

    /**
     * Constructs a <code>PostSetPostCustomizedButtonBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostSetPostCustomizedButtonBody} obj Optional instance to populate.
     * @return {module:model/PostSetPostCustomizedButtonBody} The populated <code>PostSetPostCustomizedButtonBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostSetPostCustomizedButtonBody();

            if (data.hasOwnProperty('customized_button')) {
                obj['customized_button'] = PostCustomizedButton.constructFromObject(data['customized_button']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostSetPostCustomizedButtonBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostSetPostCustomizedButtonBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostSetPostCustomizedButtonBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `customized_button`
        if (data['customized_button']) { // data not null
          PostCustomizedButton.validateJSON(data['customized_button']);
        }

        return true;
    }

/**
     * @return {module:model/PostCustomizedButton}
     */
    getCustomizedButton() {
        return this.customized_button;
    }

    /**
     * @param {module:model/PostCustomizedButton} customizedButton
     */
    setCustomizedButton(customizedButton) {
        this['customized_button'] = customizedButton;
    }

}

PostSetPostCustomizedButtonBody.RequiredProperties = ["customized_button"];

/**
 * @member {module:model/PostCustomizedButton} customized_button
 */
PostSetPostCustomizedButtonBody.prototype['customized_button'] = undefined;






export default PostSetPostCustomizedButtonBody;

