/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostPostGeneralData from './PostPostGeneralData';

/**
 * The PostEditPostV2Body model module.
 * @module model/PostEditPostV2Body
 * @version 0.1.0
 */
class PostEditPostV2Body {
    /**
     * Constructs a new <code>PostEditPostV2Body</code>.
     * @alias module:model/PostEditPostV2Body
     * @param updateMask {Array.<String>} مشخص می‌کند کدام فیلدها به‌روزرسانی شوند. از مسیرهای تودرتو مانند 'general_data.title' یا 'category_data.price' استفاده کنید. این کار تمایز بین پاک کردن یک فیلد و تغییر ندادن آن را ممکن می‌سازد.
     */
    constructor(updateMask) { 
        
        PostEditPostV2Body.initialize(this, updateMask);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, updateMask) { 
        obj['update_mask'] = updateMask;
    }

    /**
     * Constructs a <code>PostEditPostV2Body</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostEditPostV2Body} obj Optional instance to populate.
     * @return {module:model/PostEditPostV2Body} The populated <code>PostEditPostV2Body</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostEditPostV2Body();

            if (data.hasOwnProperty('update_mask')) {
                obj['update_mask'] = ApiClient.convertToType(data['update_mask'], ['String']);
            }
            if (data.hasOwnProperty('category_data')) {
                obj['category_data'] = ApiClient.convertToType(data['category_data'], Object);
            }
            if (data.hasOwnProperty('general_data')) {
                obj['general_data'] = PostPostGeneralData.constructFromObject(data['general_data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostEditPostV2Body</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostEditPostV2Body</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostEditPostV2Body.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['update_mask'])) {
            throw new Error("Expected the field `update_mask` to be an array in the JSON data but got " + data['update_mask']);
        }
        // validate the optional field `general_data`
        if (data['general_data']) { // data not null
          PostPostGeneralData.validateJSON(data['general_data']);
        }

        return true;
    }

/**
     * Returns مشخص می‌کند کدام فیلدها به‌روزرسانی شوند. از مسیرهای تودرتو مانند 'general_data.title' یا 'category_data.price' استفاده کنید. این کار تمایز بین پاک کردن یک فیلد و تغییر ندادن آن را ممکن می‌سازد.
     * @return {Array.<String>}
     */
    getUpdateMask() {
        return this.update_mask;
    }

    /**
     * Sets مشخص می‌کند کدام فیلدها به‌روزرسانی شوند. از مسیرهای تودرتو مانند 'general_data.title' یا 'category_data.price' استفاده کنید. این کار تمایز بین پاک کردن یک فیلد و تغییر ندادن آن را ممکن می‌سازد.
     * @param {Array.<String>} updateMask مشخص می‌کند کدام فیلدها به‌روزرسانی شوند. از مسیرهای تودرتو مانند 'general_data.title' یا 'category_data.price' استفاده کنید. این کار تمایز بین پاک کردن یک فیلد و تغییر ندادن آن را ممکن می‌سازد.
     */
    setUpdateMask(updateMask) {
        this['update_mask'] = updateMask;
    }
/**
     * Returns فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     * @return {Object}
     */
    getCategoryData() {
        return this.category_data;
    }

    /**
     * Sets فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     * @param {Object} categoryData فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     */
    setCategoryData(categoryData) {
        this['category_data'] = categoryData;
    }
/**
     * @return {module:model/PostPostGeneralData}
     */
    getGeneralData() {
        return this.general_data;
    }

    /**
     * @param {module:model/PostPostGeneralData} generalData
     */
    setGeneralData(generalData) {
        this['general_data'] = generalData;
    }

}

PostEditPostV2Body.RequiredProperties = ["update_mask"];

/**
 * مشخص می‌کند کدام فیلدها به‌روزرسانی شوند. از مسیرهای تودرتو مانند 'general_data.title' یا 'category_data.price' استفاده کنید. این کار تمایز بین پاک کردن یک فیلد و تغییر ندادن آن را ممکن می‌سازد.
 * @member {Array.<String>} update_mask
 */
PostEditPostV2Body.prototype['update_mask'] = undefined;

/**
 * فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
 * @member {Object} category_data
 */
PostEditPostV2Body.prototype['category_data'] = undefined;

/**
 * @member {module:model/PostPostGeneralData} general_data
 */
PostEditPostV2Body.prototype['general_data'] = undefined;






export default PostEditPostV2Body;

