/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PostPostGeneralData from './PostPostGeneralData';

/**
 * The PostSubmitPostV2Request model module.
 * @module model/PostSubmitPostV2Request
 * @version 0.1.0
 */
class PostSubmitPostV2Request {
    /**
     * Constructs a new <code>PostSubmitPostV2Request</code>.
     * @alias module:model/PostSubmitPostV2Request
     * @param businessToken {String} توکن کسب‌وکاری که این آگهی متعلق به آن می‌شود
     * @param categoryFields {Object} فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     * @param generalData {module:model/PostPostGeneralData} 
     */
    constructor(businessToken, categoryFields, generalData) { 
        
        PostSubmitPostV2Request.initialize(this, businessToken, categoryFields, generalData);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, businessToken, categoryFields, generalData) { 
        obj['business_token'] = businessToken;
        obj['category_fields'] = categoryFields;
        obj['general_data'] = generalData;
    }

    /**
     * Constructs a <code>PostSubmitPostV2Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostSubmitPostV2Request} obj Optional instance to populate.
     * @return {module:model/PostSubmitPostV2Request} The populated <code>PostSubmitPostV2Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostSubmitPostV2Request();

            if (data.hasOwnProperty('business_token')) {
                obj['business_token'] = ApiClient.convertToType(data['business_token'], 'String');
            }
            if (data.hasOwnProperty('category_fields')) {
                obj['category_fields'] = ApiClient.convertToType(data['category_fields'], Object);
            }
            if (data.hasOwnProperty('general_data')) {
                obj['general_data'] = PostPostGeneralData.constructFromObject(data['general_data']);
            }
            if (data.hasOwnProperty('landline_numbers')) {
                obj['landline_numbers'] = ApiClient.convertToType(data['landline_numbers'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostSubmitPostV2Request</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostSubmitPostV2Request</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostSubmitPostV2Request.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['business_token'] && !(typeof data['business_token'] === 'string' || data['business_token'] instanceof String)) {
            throw new Error("Expected the field `business_token` to be a primitive type in the JSON string but got " + data['business_token']);
        }
        // validate the optional field `general_data`
        if (data['general_data']) { // data not null
          PostPostGeneralData.validateJSON(data['general_data']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['landline_numbers'])) {
            throw new Error("Expected the field `landline_numbers` to be an array in the JSON data but got " + data['landline_numbers']);
        }

        return true;
    }

/**
     * Returns توکن کسب‌وکاری که این آگهی متعلق به آن می‌شود
     * @return {String}
     */
    getBusinessToken() {
        return this.business_token;
    }

    /**
     * Sets توکن کسب‌وکاری که این آگهی متعلق به آن می‌شود
     * @param {String} businessToken توکن کسب‌وکاری که این آگهی متعلق به آن می‌شود
     */
    setBusinessToken(businessToken) {
        this['business_token'] = businessToken;
    }
/**
     * Returns فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     * @return {Object}
     */
    getCategoryFields() {
        return this.category_fields;
    }

    /**
     * Sets فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     * @param {Object} categoryFields فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
     */
    setCategoryFields(categoryFields) {
        this['category_fields'] = categoryFields;
    }
/**
     * @return {module:model/PostPostGeneralData}
     */
    getGeneralData() {
        return this.general_data;
    }

    /**
     * @param {module:model/PostPostGeneralData} generalData
     */
    setGeneralData(generalData) {
        this['general_data'] = generalData;
    }
/**
     * Returns شماره‌های ثابت برای افزودن به آگهی
     * @return {Array.<String>}
     */
    getLandlineNumbers() {
        return this.landline_numbers;
    }

    /**
     * Sets شماره‌های ثابت برای افزودن به آگهی
     * @param {Array.<String>} landlineNumbers شماره‌های ثابت برای افزودن به آگهی
     */
    setLandlineNumbers(landlineNumbers) {
        this['landline_numbers'] = landlineNumbers;
    }

}

PostSubmitPostV2Request.RequiredProperties = ["business_token", "category_fields", "general_data"];

/**
 * توکن کسب‌وکاری که این آگهی متعلق به آن می‌شود
 * @member {String} business_token
 */
PostSubmitPostV2Request.prototype['business_token'] = undefined;

/**
 * فیلدهای مختص دسته‌بندی که باید مطابق schema تکمیل شوند. schema را اینجا ببینید: https://kenar.divar.dev/openapi-doc/assets-get-submit-schema/
 * @member {Object} category_fields
 */
PostSubmitPostV2Request.prototype['category_fields'] = undefined;

/**
 * @member {module:model/PostPostGeneralData} general_data
 */
PostSubmitPostV2Request.prototype['general_data'] = undefined;

/**
 * شماره‌های ثابت برای افزودن به آگهی
 * @member {Array.<String>} landline_numbers
 */
PostSubmitPostV2Request.prototype['landline_numbers'] = undefined;






export default PostSubmitPostV2Request;

