/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PostRoomsCount.
* @enum {}
* @readonly
*/
export default class PostRoomsCount {
    
        /**
         * value: "ROOMS_COUNT_0"
         * @const
         */
        "ROOMS_COUNT_0" = "ROOMS_COUNT_0";

    
        /**
         * value: "ROOMS_COUNT_1"
         * @const
         */
        "ROOMS_COUNT_1" = "ROOMS_COUNT_1";

    
        /**
         * value: "ROOMS_COUNT_2"
         * @const
         */
        "ROOMS_COUNT_2" = "ROOMS_COUNT_2";

    
        /**
         * value: "ROOMS_COUNT_3"
         * @const
         */
        "ROOMS_COUNT_3" = "ROOMS_COUNT_3";

    
        /**
         * value: "ROOMS_COUNT_4"
         * @const
         */
        "ROOMS_COUNT_4" = "ROOMS_COUNT_4";

    
        /**
         * value: "ROOMS_COUNT_5_OR_MORE"
         * @const
         */
        "ROOMS_COUNT_5_OR_MORE" = "ROOMS_COUNT_5_OR_MORE";

    

    /**
    * Returns a <code>PostRoomsCount</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PostRoomsCount} The enum <code>PostRoomsCount</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

