/**
 * divar_interface/open_platform/chatapi/chatapi.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchPostItemPrice model module.
 * @module model/SearchPostItemPrice
 * @version 0.1.0
 */
class SearchPostItemPrice {
    /**
     * Constructs a new <code>SearchPostItemPrice</code>.
     * @alias module:model/SearchPostItemPrice
     */
    constructor() { 
        
        SearchPostItemPrice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchPostItemPrice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchPostItemPrice} obj Optional instance to populate.
     * @return {module:model/SearchPostItemPrice} The populated <code>SearchPostItemPrice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchPostItemPrice();

            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchPostItemPrice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchPostItemPrice</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['mode'] && !(typeof data['mode'] === 'string' || data['mode'] instanceof String)) {
            throw new Error("Expected the field `mode` to be a primitive type in the JSON string but got " + data['mode']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getMode() {
        return this.mode;
    }

    /**
     * @param {String} mode
     */
    setMode(mode) {
        this['mode'] = mode;
    }
/**
     * @return {String}
     */
    getValue() {
        return this.value;
    }

    /**
     * @param {String} value
     */
    setValue(value) {
        this['value'] = value;
    }

}



/**
 * @member {String} mode
 */
SearchPostItemPrice.prototype['mode'] = undefined;

/**
 * @member {String} value
 */
SearchPostItemPrice.prototype['value'] = undefined;






export default SearchPostItemPrice;

