/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchPostItemVehiclesFields model module.
 * @module model/SearchPostItemVehiclesFields
 * @version 0.1.0
 */
class SearchPostItemVehiclesFields {
    /**
     * Constructs a new <code>SearchPostItemVehiclesFields</code>.
     * @alias module:model/SearchPostItemVehiclesFields
     */
    constructor() { 
        
        SearchPostItemVehiclesFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchPostItemVehiclesFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchPostItemVehiclesFields} obj Optional instance to populate.
     * @return {module:model/SearchPostItemVehiclesFields} The populated <code>SearchPostItemVehiclesFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchPostItemVehiclesFields();

            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'String');
            }
            if (data.hasOwnProperty('installment_sale')) {
                obj['installment_sale'] = ApiClient.convertToType(data['installment_sale'], 'String');
            }
            if (data.hasOwnProperty('custom_post_subtitle')) {
                obj['custom_post_subtitle'] = ApiClient.convertToType(data['custom_post_subtitle'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchPostItemVehiclesFields</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchPostItemVehiclesFields</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['usage'] && !(typeof data['usage'] === 'string' || data['usage'] instanceof String)) {
            throw new Error("Expected the field `usage` to be a primitive type in the JSON string but got " + data['usage']);
        }
        // ensure the json data is a string
        if (data['installment_sale'] && !(typeof data['installment_sale'] === 'string' || data['installment_sale'] instanceof String)) {
            throw new Error("Expected the field `installment_sale` to be a primitive type in the JSON string but got " + data['installment_sale']);
        }
        // ensure the json data is a string
        if (data['custom_post_subtitle'] && !(typeof data['custom_post_subtitle'] === 'string' || data['custom_post_subtitle'] instanceof String)) {
            throw new Error("Expected the field `custom_post_subtitle` to be a primitive type in the JSON string but got " + data['custom_post_subtitle']);
        }

        return true;
    }

/**
     * @return {String}
     */
    getUsage() {
        return this.usage;
    }

    /**
     * @param {String} usage
     */
    setUsage(usage) {
        this['usage'] = usage;
    }
/**
     * @return {String}
     */
    getInstallmentSale() {
        return this.installment_sale;
    }

    /**
     * @param {String} installmentSale
     */
    setInstallmentSale(installmentSale) {
        this['installment_sale'] = installmentSale;
    }
/**
     * @return {String}
     */
    getCustomPostSubtitle() {
        return this.custom_post_subtitle;
    }

    /**
     * @param {String} customPostSubtitle
     */
    setCustomPostSubtitle(customPostSubtitle) {
        this['custom_post_subtitle'] = customPostSubtitle;
    }

}



/**
 * @member {String} usage
 */
SearchPostItemVehiclesFields.prototype['usage'] = undefined;

/**
 * @member {String} installment_sale
 */
SearchPostItemVehiclesFields.prototype['installment_sale'] = undefined;

/**
 * @member {String} custom_post_subtitle
 */
SearchPostItemVehiclesFields.prototype['custom_post_subtitle'] = undefined;






export default SearchPostItemVehiclesFields;

