/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SemanticCreateUserSemanticBody model module.
 * @module model/SemanticCreateUserSemanticBody
 * @version 0.1.0
 */
class SemanticCreateUserSemanticBody {
    /**
     * Constructs a new <code>SemanticCreateUserSemanticBody</code>.
     * @alias module:model/SemanticCreateUserSemanticBody
     * @param phone {String} شماره موبایل کاربر
     * @param semantic {Object.<String, String>} مپ key-value اطلاعات معنایی برای ذخیره
     */
    constructor(phone, semantic) { 
        
        SemanticCreateUserSemanticBody.initialize(this, phone, semantic);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, phone, semantic) { 
        obj['phone'] = phone;
        obj['semantic'] = semantic;
    }

    /**
     * Constructs a <code>SemanticCreateUserSemanticBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SemanticCreateUserSemanticBody} obj Optional instance to populate.
     * @return {module:model/SemanticCreateUserSemanticBody} The populated <code>SemanticCreateUserSemanticBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SemanticCreateUserSemanticBody();

            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('semantic')) {
                obj['semantic'] = ApiClient.convertToType(data['semantic'], {'String': 'String'});
            }
            if (data.hasOwnProperty('cost')) {
                obj['cost'] = ApiClient.convertToType(data['cost'], 'Number');
            }
            if (data.hasOwnProperty('ticket_uuid')) {
                obj['ticket_uuid'] = ApiClient.convertToType(data['ticket_uuid'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SemanticCreateUserSemanticBody</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SemanticCreateUserSemanticBody</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SemanticCreateUserSemanticBody.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['ticket_uuid'] && !(typeof data['ticket_uuid'] === 'string' || data['ticket_uuid'] instanceof String)) {
            throw new Error("Expected the field `ticket_uuid` to be a primitive type in the JSON string but got " + data['ticket_uuid']);
        }

        return true;
    }

/**
     * Returns شماره موبایل کاربر
     * @return {String}
     */
    getPhone() {
        return this.phone;
    }

    /**
     * Sets شماره موبایل کاربر
     * @param {String} phone شماره موبایل کاربر
     */
    setPhone(phone) {
        this['phone'] = phone;
    }
/**
     * Returns مپ key-value اطلاعات معنایی برای ذخیره
     * @return {Object.<String, String>}
     */
    getSemantic() {
        return this.semantic;
    }

    /**
     * Sets مپ key-value اطلاعات معنایی برای ذخیره
     * @param {Object.<String, String>} semantic مپ key-value اطلاعات معنایی برای ذخیره
     */
    setSemantic(semantic) {
        this['semantic'] = semantic;
    }
/**
     * Returns هزینه مرتبط با عملیات
     * @return {Number}
     */
    getCost() {
        return this.cost;
    }

    /**
     * Sets هزینه مرتبط با عملیات
     * @param {Number} cost هزینه مرتبط با عملیات
     */
    setCost(cost) {
        this['cost'] = cost;
    }
/**
     * Returns UUID تیکت پرداخت (اختیاری)
     * @return {String}
     */
    getTicketUuid() {
        return this.ticket_uuid;
    }

    /**
     * Sets UUID تیکت پرداخت (اختیاری)
     * @param {String} ticketUuid UUID تیکت پرداخت (اختیاری)
     */
    setTicketUuid(ticketUuid) {
        this['ticket_uuid'] = ticketUuid;
    }

}

SemanticCreateUserSemanticBody.RequiredProperties = ["phone", "semantic"];

/**
 * شماره موبایل کاربر
 * @member {String} phone
 */
SemanticCreateUserSemanticBody.prototype['phone'] = undefined;

/**
 * مپ key-value اطلاعات معنایی برای ذخیره
 * @member {Object.<String, String>} semantic
 */
SemanticCreateUserSemanticBody.prototype['semantic'] = undefined;

/**
 * هزینه مرتبط با عملیات
 * @member {Number} cost
 */
SemanticCreateUserSemanticBody.prototype['cost'] = undefined;

/**
 * UUID تیکت پرداخت (اختیاری)
 * @member {String} ticket_uuid
 */
SemanticCreateUserSemanticBody.prototype['ticket_uuid'] = undefined;






export default SemanticCreateUserSemanticBody;

