/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class WidgetsActionType.
* @enum {}
* @readonly
*/
export default class WidgetsActionType {
    
        /**
         * value: "MAP_PREVIEW"
         * @const
         */
        "MAP_PREVIEW" = "MAP_PREVIEW";

    
        /**
         * value: "CALL_SUPPORT"
         * @const
         */
        "CALL_SUPPORT" = "CALL_SUPPORT";

    
        /**
         * value: "MANAGE_POST"
         * @const
         */
        "MANAGE_POST" = "MANAGE_POST";

    
        /**
         * value: "VIEW_POST"
         * @const
         */
        "VIEW_POST" = "VIEW_POST";

    
        /**
         * value: "USER_AUTHENTICATION"
         * @const
         */
        "USER_AUTHENTICATION" = "USER_AUTHENTICATION";

    
        /**
         * value: "PAYMENT_HISTORY"
         * @const
         */
        "PAYMENT_HISTORY" = "PAYMENT_HISTORY";

    
        /**
         * value: "CLAIM_POST"
         * @const
         */
        "CLAIM_POST" = "CLAIM_POST";

    
        /**
         * value: "ARCHIVE_POST"
         * @const
         */
        "ARCHIVE_POST" = "ARCHIVE_POST";

    
        /**
         * value: "EDIT_POST"
         * @const
         */
        "EDIT_POST" = "EDIT_POST";

    
        /**
         * value: "PREVIEW_POST"
         * @const
         */
        "PREVIEW_POST" = "PREVIEW_POST";

    
        /**
         * value: "UPGRADE_POST"
         * @const
         */
        "UPGRADE_POST" = "UPGRADE_POST";

    
        /**
         * value: "LOAD_PAGE"
         * @const
         */
        "LOAD_PAGE" = "LOAD_PAGE";

    
        /**
         * value: "AUTH_NATIONAL_ID"
         * @const
         */
        "AUTH_NATIONAL_ID" = "AUTH_NATIONAL_ID";

    
        /**
         * value: "PERSONAL_SUBMIT_POST"
         * @const
         */
        "PERSONAL_SUBMIT_POST" = "PERSONAL_SUBMIT_POST";

    
        /**
         * value: "OPEN_WEB_PAGE"
         * @const
         */
        "OPEN_WEB_PAGE" = "OPEN_WEB_PAGE";

    
        /**
         * value: "LOAD_PAYMENT_DETAILS"
         * @const
         */
        "LOAD_PAYMENT_DETAILS" = "LOAD_PAYMENT_DETAILS";

    
        /**
         * value: "LANDLINE_VERIFICATION"
         * @const
         */
        "LANDLINE_VERIFICATION" = "LANDLINE_VERIFICATION";

    
        /**
         * value: "LOGOUT"
         * @const
         */
        "LOGOUT" = "LOGOUT";

    
        /**
         * value: "OPEN_SUPPORT_PAGE"
         * @const
         */
        "OPEN_SUPPORT_PAGE" = "OPEN_SUPPORT_PAGE";

    
        /**
         * value: "USER_SUGGESTION_PAGE"
         * @const
         */
        "USER_SUGGESTION_PAGE" = "USER_SUGGESTION_PAGE";

    
        /**
         * value: "CATEGORY_SUGGESTION"
         * @const
         */
        "CATEGORY_SUGGESTION" = "CATEGORY_SUGGESTION";

    
        /**
         * value: "WALLET_SETTINGS_PAGE"
         * @const
         */
        "WALLET_SETTINGS_PAGE" = "WALLET_SETTINGS_PAGE";

    
        /**
         * value: "OPEN_POSTLIST_PAGE"
         * @const
         */
        "OPEN_POSTLIST_PAGE" = "OPEN_POSTLIST_PAGE";

    
        /**
         * value: "WALLET_BALANCE_PAGE"
         * @const
         */
        "WALLET_BALANCE_PAGE" = "WALLET_BALANCE_PAGE";

    
        /**
         * value: "OPEN_PAGE"
         * @const
         */
        "OPEN_PAGE" = "OPEN_PAGE";

    
        /**
         * value: "WALLET_CALL_SUPPORT"
         * @const
         */
        "WALLET_CALL_SUPPORT" = "WALLET_CALL_SUPPORT";

    
        /**
         * value: "OPEN_SCHEMA_PAGE"
         * @const
         */
        "OPEN_SCHEMA_PAGE" = "OPEN_SCHEMA_PAGE";

    
        /**
         * value: "COPY_TO_CLIPBOARD"
         * @const
         */
        "COPY_TO_CLIPBOARD" = "COPY_TO_CLIPBOARD";

    
        /**
         * value: "POP_PAGES_AND_PERFORM_ACTION"
         * @const
         */
        "POP_PAGES_AND_PERFORM_ACTION" = "POP_PAGES_AND_PERFORM_ACTION";

    
        /**
         * value: "MARKETPLACE_SHARE_STORE_LANDING"
         * @const
         */
        "MARKETPLACE_SHARE_STORE_LANDING" = "MARKETPLACE_SHARE_STORE_LANDING";

    
        /**
         * value: "OPEN_POST_SUGGESTION_POST"
         * @const
         */
        "OPEN_POST_SUGGESTION_POST" = "OPEN_POST_SUGGESTION_POST";

    
        /**
         * value: "MESSAGE"
         * @const
         */
        "MESSAGE" = "MESSAGE";

    
        /**
         * value: "MY_DIVAR_MANAGE_POST"
         * @const
         */
        "MY_DIVAR_MANAGE_POST" = "MY_DIVAR_MANAGE_POST";

    
        /**
         * value: "CLOSE_PAGE"
         * @const
         */
        "CLOSE_PAGE" = "CLOSE_PAGE";

    
        /**
         * value: "POST_GET_CONTACT"
         * @const
         */
        "POST_GET_CONTACT" = "POST_GET_CONTACT";

    
        /**
         * value: "POST_VOIP_CALL"
         * @const
         */
        "POST_VOIP_CALL" = "POST_VOIP_CALL";

    
        /**
         * value: "OPEN_POST_REPORT"
         * @const
         */
        "OPEN_POST_REPORT" = "OPEN_POST_REPORT";

    
        /**
         * value: "OPEN_POST_CHAT"
         * @const
         */
        "OPEN_POST_CHAT" = "OPEN_POST_CHAT";

    
        /**
         * value: "FILTERABLE_SEARCH_RESULT"
         * @const
         */
        "FILTERABLE_SEARCH_RESULT" = "FILTERABLE_SEARCH_RESULT";

    
        /**
         * value: "OPEN_WEB_PAGE_ALERT"
         * @const
         */
        "OPEN_WEB_PAGE_ALERT" = "OPEN_WEB_PAGE_ALERT";

    
        /**
         * value: "START_PAYMENT"
         * @const
         */
        "START_PAYMENT" = "START_PAYMENT";

    
        /**
         * value: "NOTE"
         * @const
         */
        "NOTE" = "NOTE";

    
        /**
         * value: "BOOKMARK"
         * @const
         */
        "BOOKMARK" = "BOOKMARK";

    
        /**
         * value: "MY_DIVAR_POSTS"
         * @const
         */
        "MY_DIVAR_POSTS" = "MY_DIVAR_POSTS";

    
        /**
         * value: "MY_DIVAR_BOOKMARKS"
         * @const
         */
        "MY_DIVAR_BOOKMARKS" = "MY_DIVAR_BOOKMARKS";

    
        /**
         * value: "MY_DIVAR_RECENT_SEEN"
         * @const
         */
        "MY_DIVAR_RECENT_SEEN" = "MY_DIVAR_RECENT_SEEN";

    
        /**
         * value: "MY_DIVAR_NOTES"
         * @const
         */
        "MY_DIVAR_NOTES" = "MY_DIVAR_NOTES";

    
        /**
         * value: "OPEN_MAP"
         * @const
         */
        "OPEN_MAP" = "OPEN_MAP";

    
        /**
         * value: "LOAD_MODAL_PAGE"
         * @const
         */
        "LOAD_MODAL_PAGE" = "LOAD_MODAL_PAGE";

    
        /**
         * value: "ANGOOLAK_LOGIN"
         * @const
         */
        "ANGOOLAK_LOGIN" = "ANGOOLAK_LOGIN";

    
        /**
         * value: "LOAD_BOTTOM_SHEET"
         * @const
         */
        "LOAD_BOTTOM_SHEET" = "LOAD_BOTTOM_SHEET";

    
        /**
         * value: "CHAT_BLOCK_PEER"
         * @const
         */
        "CHAT_BLOCK_PEER" = "CHAT_BLOCK_PEER";

    
        /**
         * value: "CHAT_REPORT_PEER"
         * @const
         */
        "CHAT_REPORT_PEER" = "CHAT_REPORT_PEER";

    
        /**
         * value: "MY_DIVAR_BOOKMARKS_AND_NOTES"
         * @const
         */
        "MY_DIVAR_BOOKMARKS_AND_NOTES" = "MY_DIVAR_BOOKMARKS_AND_NOTES";

    
        /**
         * value: "MY_DIVAR_SETTINGS"
         * @const
         */
        "MY_DIVAR_SETTINGS" = "MY_DIVAR_SETTINGS";

    
        /**
         * value: "LOGIN"
         * @const
         */
        "LOGIN" = "LOGIN";

    
        /**
         * value: "SHOW_WIDE_BUTTON_ALERT"
         * @const
         */
        "SHOW_WIDE_BUTTON_ALERT" = "SHOW_WIDE_BUTTON_ALERT";

    
        /**
         * value: "IN_APP_UPDATE"
         * @const
         */
        "IN_APP_UPDATE" = "IN_APP_UPDATE";

    
        /**
         * value: "MY_PAYMENT_HISTORY"
         * @const
         */
        "MY_PAYMENT_HISTORY" = "MY_PAYMENT_HISTORY";

    
        /**
         * value: "SUBMIT_CALL_FEEDBACK"
         * @const
         */
        "SUBMIT_CALL_FEEDBACK" = "SUBMIT_CALL_FEEDBACK";

    
        /**
         * value: "HISTORY_BACK"
         * @const
         */
        "HISTORY_BACK" = "HISTORY_BACK";

    
        /**
         * value: "SERVICES_VIEW_PROFILE"
         * @const
         */
        "SERVICES_VIEW_PROFILE" = "SERVICES_VIEW_PROFILE";

    
        /**
         * value: "BLACKLIST_APPEAL_OPEN_SUBMISSION_FORM_PAGE"
         * @const
         */
        "BLACKLIST_APPEAL_OPEN_SUBMISSION_FORM_PAGE" = "BLACKLIST_APPEAL_OPEN_SUBMISSION_FORM_PAGE";

    
        /**
         * value: "BLACKLIST_APPEAL_OPEN_STATUS_PAGE"
         * @const
         */
        "BLACKLIST_APPEAL_OPEN_STATUS_PAGE" = "BLACKLIST_APPEAL_OPEN_STATUS_PAGE";

    
        /**
         * value: "SERVICES_OPEN_REPORT"
         * @const
         */
        "SERVICES_OPEN_REPORT" = "SERVICES_OPEN_REPORT";

    
        /**
         * value: "DELETE_POST_NOTE"
         * @const
         */
        "DELETE_POST_NOTE" = "DELETE_POST_NOTE";

    
        /**
         * value: "DELETE_POST_BOOKMARK"
         * @const
         */
        "DELETE_POST_BOOKMARK" = "DELETE_POST_BOOKMARK";

    
        /**
         * value: "OPEN_FORM_PAGE"
         * @const
         */
        "OPEN_FORM_PAGE" = "OPEN_FORM_PAGE";

    
        /**
         * value: "POP_SINGLE_PAGE_AND_PERFORM_ACTION"
         * @const
         */
        "POP_SINGLE_PAGE_AND_PERFORM_ACTION" = "POP_SINGLE_PAGE_AND_PERFORM_ACTION";

    
        /**
         * value: "DISMISS_PAGES_AND_PERFORM_ACTION"
         * @const
         */
        "DISMISS_PAGES_AND_PERFORM_ACTION" = "DISMISS_PAGES_AND_PERFORM_ACTION";

    
        /**
         * value: "OPEN_USER_VERIFICATION_PAGE"
         * @const
         */
        "OPEN_USER_VERIFICATION_PAGE" = "OPEN_USER_VERIFICATION_PAGE";

    
        /**
         * value: "OPEN_BOTTOM_SHEET"
         * @const
         */
        "OPEN_BOTTOM_SHEET" = "OPEN_BOTTOM_SHEET";

    
        /**
         * value: "SHARE"
         * @const
         */
        "SHARE" = "SHARE";

    
        /**
         * value: "CHAT_SEND_IMAGE_WITH_CAMERA"
         * @const
         */
        "CHAT_SEND_IMAGE_WITH_CAMERA" = "CHAT_SEND_IMAGE_WITH_CAMERA";

    
        /**
         * value: "CHAT_SEND_IMAGE_FROM_GALLERY"
         * @const
         */
        "CHAT_SEND_IMAGE_FROM_GALLERY" = "CHAT_SEND_IMAGE_FROM_GALLERY";

    
        /**
         * value: "CHAT_SEND_VIDEO_WITH_CAMERA"
         * @const
         */
        "CHAT_SEND_VIDEO_WITH_CAMERA" = "CHAT_SEND_VIDEO_WITH_CAMERA";

    
        /**
         * value: "CHAT_SEND_FILE"
         * @const
         */
        "CHAT_SEND_FILE" = "CHAT_SEND_FILE";

    
        /**
         * value: "CHAT_SHARE_CONTACT"
         * @const
         */
        "CHAT_SHARE_CONTACT" = "CHAT_SHARE_CONTACT";

    
        /**
         * value: "CHAT_SHARE_LOCATION"
         * @const
         */
        "CHAT_SHARE_LOCATION" = "CHAT_SHARE_LOCATION";

    
        /**
         * value: "LOAD_WEB_VIEW_PAGE"
         * @const
         */
        "LOAD_WEB_VIEW_PAGE" = "LOAD_WEB_VIEW_PAGE";

    
        /**
         * value: "POP_STACK_AND_GO_TO_BUSINESS_PANEL"
         * @const
         */
        "POP_STACK_AND_GO_TO_BUSINESS_PANEL" = "POP_STACK_AND_GO_TO_BUSINESS_PANEL";

    
        /**
         * value: "CHAT_SEND_SUGGESTION"
         * @const
         */
        "CHAT_SEND_SUGGESTION" = "CHAT_SEND_SUGGESTION";

    
        /**
         * value: "MAKE_NETWORK_CALL"
         * @const
         */
        "MAKE_NETWORK_CALL" = "MAKE_NETWORK_CALL";

    
        /**
         * value: "OPEN_MAP_DISCOVERY"
         * @const
         */
        "OPEN_MAP_DISCOVERY" = "OPEN_MAP_DISCOVERY";

    
        /**
         * value: "SERVICES_OPEN_PROFILE_SETTINGS_PAGE"
         * @const
         */
        "SERVICES_OPEN_PROFILE_SETTINGS_PAGE" = "SERVICES_OPEN_PROFILE_SETTINGS_PAGE";

    
        /**
         * value: "SERVICES_OPEN_PROFILE_PREVIEW_PAGE"
         * @const
         */
        "SERVICES_OPEN_PROFILE_PREVIEW_PAGE" = "SERVICES_OPEN_PROFILE_PREVIEW_PAGE";

    
        /**
         * value: "SERVICES_OPEN_LADDER_PAGE"
         * @const
         */
        "SERVICES_OPEN_LADDER_PAGE" = "SERVICES_OPEN_LADDER_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_NAME_AND_ABOUT_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_NAME_AND_ABOUT_PAGE" = "SERVICES_OPEN_EDIT_NAME_AND_ABOUT_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_EXPERTISE_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_EXPERTISE_PAGE" = "SERVICES_OPEN_EDIT_EXPERTISE_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_WORK_SAMPLES_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_WORK_SAMPLES_PAGE" = "SERVICES_OPEN_EDIT_WORK_SAMPLES_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_WORKING_HOURS_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_WORKING_HOURS_PAGE" = "SERVICES_OPEN_EDIT_WORKING_HOURS_PAGE";

    
        /**
         * value: "SERVICES_OPEN_STATISTICS_PAGE"
         * @const
         */
        "SERVICES_OPEN_STATISTICS_PAGE" = "SERVICES_OPEN_STATISTICS_PAGE";

    
        /**
         * value: "SERVICES_OPEN_LADDER_CREDIT_PAGE"
         * @const
         */
        "SERVICES_OPEN_LADDER_CREDIT_PAGE" = "SERVICES_OPEN_LADDER_CREDIT_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_GENERAL_INFO_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_GENERAL_INFO_PAGE" = "SERVICES_OPEN_EDIT_GENERAL_INFO_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_EXPERTISE_PRICING_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_EXPERTISE_PRICING_PAGE" = "SERVICES_OPEN_EDIT_EXPERTISE_PRICING_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_ACTIVITY_NEIGHBORHOODS_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_ACTIVITY_NEIGHBORHOODS_PAGE" = "SERVICES_OPEN_EDIT_ACTIVITY_NEIGHBORHOODS_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_CONTACT_INFO_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_CONTACT_INFO_PAGE" = "SERVICES_OPEN_EDIT_CONTACT_INFO_PAGE";

    
        /**
         * value: "SERVICES_OPEN_EDIT_WEBSITE_LINK_PAGE"
         * @const
         */
        "SERVICES_OPEN_EDIT_WEBSITE_LINK_PAGE" = "SERVICES_OPEN_EDIT_WEBSITE_LINK_PAGE";

    
        /**
         * value: "SERVICES_OPEN_ADD_LANDLINE_PAGE"
         * @const
         */
        "SERVICES_OPEN_ADD_LANDLINE_PAGE" = "SERVICES_OPEN_ADD_LANDLINE_PAGE";

    
        /**
         * value: "SERVICES_OPEN_LIST_EXPERTISE_PRICING_PAGE"
         * @const
         */
        "SERVICES_OPEN_LIST_EXPERTISE_PRICING_PAGE" = "SERVICES_OPEN_LIST_EXPERTISE_PRICING_PAGE";

    
        /**
         * value: "BLACKLIST_APPEAL_OPEN_CHANGE_OWNERSHIP_PAGE"
         * @const
         */
        "BLACKLIST_APPEAL_OPEN_CHANGE_OWNERSHIP_PAGE" = "BLACKLIST_APPEAL_OPEN_CHANGE_OWNERSHIP_PAGE";

    
        /**
         * value: "OPEN_REVOKE_USER_VERIFICATION_PAGE"
         * @const
         */
        "OPEN_REVOKE_USER_VERIFICATION_PAGE" = "OPEN_REVOKE_USER_VERIFICATION_PAGE";

    
        /**
         * value: "OPEN_MY_WALLET_PAGE"
         * @const
         */
        "OPEN_MY_WALLET_PAGE" = "OPEN_MY_WALLET_PAGE";

    
        /**
         * value: "CHAT_SEND_RECENT_IMAGES"
         * @const
         */
        "CHAT_SEND_RECENT_IMAGES" = "CHAT_SEND_RECENT_IMAGES";

    
        /**
         * value: "BULK_LADDER_WITH_PAYMENT"
         * @const
         */
        "BULK_LADDER_WITH_PAYMENT" = "BULK_LADDER_WITH_PAYMENT";

    
        /**
         * value: "CHAT_SPAM_CONVERSATION"
         * @const
         */
        "CHAT_SPAM_CONVERSATION" = "CHAT_SPAM_CONVERSATION";

    
        /**
         * value: "SERVICES_START_ACTIVATION_PAYMENT"
         * @const
         */
        "SERVICES_START_ACTIVATION_PAYMENT" = "SERVICES_START_ACTIVATION_PAYMENT";

    
        /**
         * value: "SERVICES_OPEN_REMOVE_LANDLINE_PAGE"
         * @const
         */
        "SERVICES_OPEN_REMOVE_LANDLINE_PAGE" = "SERVICES_OPEN_REMOVE_LANDLINE_PAGE";

    
        /**
         * value: "OPEN_HOME_PAGE"
         * @const
         */
        "OPEN_HOME_PAGE" = "OPEN_HOME_PAGE";

    
        /**
         * value: "PAYMENT_HISTORY_DETAILS"
         * @const
         */
        "PAYMENT_HISTORY_DETAILS" = "PAYMENT_HISTORY_DETAILS";

    
        /**
         * value: "PAYMENT_ISSUE_INVOICE"
         * @const
         */
        "PAYMENT_ISSUE_INVOICE" = "PAYMENT_ISSUE_INVOICE";

    
        /**
         * value: "OPEN_POSTLIST_PAGE_GRPC"
         * @const
         */
        "OPEN_POSTLIST_PAGE_GRPC" = "OPEN_POSTLIST_PAGE_GRPC";

    
        /**
         * value: "SERVICES_OPEN_WEB_REGISTRATION"
         * @const
         */
        "SERVICES_OPEN_WEB_REGISTRATION" = "SERVICES_OPEN_WEB_REGISTRATION";

    
        /**
         * value: "CAR_DEALERS_ALLOCATE_QUOTA"
         * @const
         */
        "CAR_DEALERS_ALLOCATE_QUOTA" = "CAR_DEALERS_ALLOCATE_QUOTA";

    
        /**
         * value: "MY_DIVAR_ACCESSIBILITY"
         * @const
         */
        "MY_DIVAR_ACCESSIBILITY" = "MY_DIVAR_ACCESSIBILITY";

    
        /**
         * value: "OPEN_FILTERS_PAGE"
         * @const
         */
        "OPEN_FILTERS_PAGE" = "OPEN_FILTERS_PAGE";

    
        /**
         * value: "MARKETPLACE_PURCHASE_SUBSCRIPTION_PAGE"
         * @const
         */
        "MARKETPLACE_PURCHASE_SUBSCRIPTION_PAGE" = "MARKETPLACE_PURCHASE_SUBSCRIPTION_PAGE";

    
        /**
         * value: "OPEN_WIDGET_LIST_BOTTOMSHEET"
         * @const
         */
        "OPEN_WIDGET_LIST_BOTTOMSHEET" = "OPEN_WIDGET_LIST_BOTTOMSHEET";

    
        /**
         * value: "PREMIUM_PANEL_SUBMIT_POST"
         * @const
         */
        "PREMIUM_PANEL_SUBMIT_POST" = "PREMIUM_PANEL_SUBMIT_POST";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_PANEL"
         * @const
         */
        "PREMIUM_PANEL_OPEN_PANEL" = "PREMIUM_PANEL_OPEN_PANEL";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REGISTRATION_FORM"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REGISTRATION_FORM" = "PREMIUM_PANEL_OPEN_REGISTRATION_FORM";

    
        /**
         * value: "CHAT_UNBLOCK_PEER"
         * @const
         */
        "CHAT_UNBLOCK_PEER" = "CHAT_UNBLOCK_PEER";

    
        /**
         * value: "REMOVE_WALLET_USAGE_QUOTA"
         * @const
         */
        "REMOVE_WALLET_USAGE_QUOTA" = "REMOVE_WALLET_USAGE_QUOTA";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_POST_LIST_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_POST_LIST_PAGE" = "PREMIUM_PANEL_OPEN_POST_LIST_PAGE";

    
        /**
         * value: "POP_FORM_PAGE_AND_PERFORM_ACTION"
         * @const
         */
        "POP_FORM_PAGE_AND_PERFORM_ACTION" = "POP_FORM_PAGE_AND_PERFORM_ACTION";

    
        /**
         * value: "RESUBMIT_POST"
         * @const
         */
        "RESUBMIT_POST" = "RESUBMIT_POST";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_AGENT_MANAGEMENT"
         * @const
         */
        "PREMIUM_PANEL_OPEN_AGENT_MANAGEMENT" = "PREMIUM_PANEL_OPEN_AGENT_MANAGEMENT";

    
        /**
         * value: "PREMIUM_PANEL_INVITE_AGENT"
         * @const
         */
        "PREMIUM_PANEL_INVITE_AGENT" = "PREMIUM_PANEL_INVITE_AGENT";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_AGENT_INVITATION_DETAILS"
         * @const
         */
        "PREMIUM_PANEL_OPEN_AGENT_INVITATION_DETAILS" = "PREMIUM_PANEL_OPEN_AGENT_INVITATION_DETAILS";

    
        /**
         * value: "PREMIUM_PANEL_CANCEL_AGENT_INVITATION"
         * @const
         */
        "PREMIUM_PANEL_CANCEL_AGENT_INVITATION" = "PREMIUM_PANEL_CANCEL_AGENT_INVITATION";

    
        /**
         * value: "PREMIUM_PANEL_EDIT_AGENT_INVITATION"
         * @const
         */
        "PREMIUM_PANEL_EDIT_AGENT_INVITATION" = "PREMIUM_PANEL_EDIT_AGENT_INVITATION";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_RECEIVED_INVITATIONS_LIST"
         * @const
         */
        "PREMIUM_PANEL_OPEN_RECEIVED_INVITATIONS_LIST" = "PREMIUM_PANEL_OPEN_RECEIVED_INVITATIONS_LIST";

    
        /**
         * value: "PREMIUM_PANEL_ACTION_ON_INVITATION"
         * @const
         */
        "PREMIUM_PANEL_ACTION_ON_INVITATION" = "PREMIUM_PANEL_ACTION_ON_INVITATION";

    
        /**
         * value: "OPEN_CATEGORY_SEARCH_BOTTOM_SHEET"
         * @const
         */
        "OPEN_CATEGORY_SEARCH_BOTTOM_SHEET" = "OPEN_CATEGORY_SEARCH_BOTTOM_SHEET";

    
        /**
         * value: "OPEN_WEB_CATEGORIES_MODAL"
         * @const
         */
        "OPEN_WEB_CATEGORIES_MODAL" = "OPEN_WEB_CATEGORIES_MODAL";

    
        /**
         * value: "AFTER_SUBMIT"
         * @const
         */
        "AFTER_SUBMIT" = "AFTER_SUBMIT";

    
        /**
         * value: "OPEN_RICH_WEB_VIEW"
         * @const
         */
        "OPEN_RICH_WEB_VIEW" = "OPEN_RICH_WEB_VIEW";

    
        /**
         * value: "PREMIUM_PANEL_EDIT_AGENT"
         * @const
         */
        "PREMIUM_PANEL_EDIT_AGENT" = "PREMIUM_PANEL_EDIT_AGENT";

    
        /**
         * value: "PREMIUM_PANEL_ALLOCATE_QUOTA"
         * @const
         */
        "PREMIUM_PANEL_ALLOCATE_QUOTA" = "PREMIUM_PANEL_ALLOCATE_QUOTA";

    
        /**
         * value: "PREMIUM_PANEL_REMOVE_QUOTA"
         * @const
         */
        "PREMIUM_PANEL_REMOVE_QUOTA" = "PREMIUM_PANEL_REMOVE_QUOTA";

    
        /**
         * value: "PREMIUM_PANEL_REMOVE_AGENT"
         * @const
         */
        "PREMIUM_PANEL_REMOVE_AGENT" = "PREMIUM_PANEL_REMOVE_AGENT";

    
        /**
         * value: "PREMIUM_PANEL_VIEW_AGENT_POSTS"
         * @const
         */
        "PREMIUM_PANEL_VIEW_AGENT_POSTS" = "PREMIUM_PANEL_VIEW_AGENT_POSTS";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_USAGE_REPORT_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_USAGE_REPORT_PAGE" = "PREMIUM_PANEL_OPEN_USAGE_REPORT_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_AGENT_DETAILS"
         * @const
         */
        "PREMIUM_PANEL_AGENT_DETAILS" = "PREMIUM_PANEL_AGENT_DETAILS";

    
        /**
         * value: "PREMIUM_PANEL_BRAND_MANAGEMENT"
         * @const
         */
        "PREMIUM_PANEL_BRAND_MANAGEMENT" = "PREMIUM_PANEL_BRAND_MANAGEMENT";

    
        /**
         * value: "PREMIUM_PANEL_EDIT_BRAND"
         * @const
         */
        "PREMIUM_PANEL_EDIT_BRAND" = "PREMIUM_PANEL_EDIT_BRAND";

    
        /**
         * value: "PREMIUM_PANEL_BRAND_LANDING"
         * @const
         */
        "PREMIUM_PANEL_BRAND_LANDING" = "PREMIUM_PANEL_BRAND_LANDING";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_HELP_AND_SUPPORT_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_HELP_AND_SUPPORT_PAGE" = "PREMIUM_PANEL_OPEN_HELP_AND_SUPPORT_PAGE";

    
        /**
         * value: "CLOSE_REPORT_AND_FEEDBACK_WEB_MODAL"
         * @const
         */
        "CLOSE_REPORT_AND_FEEDBACK_WEB_MODAL" = "CLOSE_REPORT_AND_FEEDBACK_WEB_MODAL";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_POST_MANAGE_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_POST_MANAGE_PAGE" = "PREMIUM_PANEL_OPEN_POST_MANAGE_PAGE";

    
        /**
         * value: "OPEN_SELECT_SEARCH_AREA_MAP"
         * @const
         */
        "OPEN_SELECT_SEARCH_AREA_MAP" = "OPEN_SELECT_SEARCH_AREA_MAP";

    
        /**
         * value: "AFTER_CALL_HISTORY_BUNDLE_ACTION_COMPLETED"
         * @const
         */
        "AFTER_CALL_HISTORY_BUNDLE_ACTION_COMPLETED" = "AFTER_CALL_HISTORY_BUNDLE_ACTION_COMPLETED";

    
        /**
         * value: "AFTER_PREMIUM_PANEL_LEAVE_BRAND"
         * @const
         */
        "AFTER_PREMIUM_PANEL_LEAVE_BRAND" = "AFTER_PREMIUM_PANEL_LEAVE_BRAND";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REGISTRATION_LANDING_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REGISTRATION_LANDING_PAGE" = "PREMIUM_PANEL_OPEN_REGISTRATION_LANDING_PAGE";

    
        /**
         * value: "OPEN_MENU"
         * @const
         */
        "OPEN_MENU" = "OPEN_MENU";

    
        /**
         * value: "LOAD_MENU"
         * @const
         */
        "LOAD_MENU" = "LOAD_MENU";

    
        /**
         * value: "OPEN_MULTI_CHOICE_MENU"
         * @const
         */
        "OPEN_MULTI_CHOICE_MENU" = "OPEN_MULTI_CHOICE_MENU";

    
        /**
         * value: "OPEN_CITY_SELECTOR"
         * @const
         */
        "OPEN_CITY_SELECTOR" = "OPEN_CITY_SELECTOR";

    
        /**
         * value: "WALLET_OPEN_MY_PAYMENTS_HISTORY_PAGE"
         * @const
         */
        "WALLET_OPEN_MY_PAYMENTS_HISTORY_PAGE" = "WALLET_OPEN_MY_PAYMENTS_HISTORY_PAGE";

    
        /**
         * value: "OPEN_MAP_POST_LIST"
         * @const
         */
        "OPEN_MAP_POST_LIST" = "OPEN_MAP_POST_LIST";

    
        /**
         * value: "CHAT_SEND_TEXT"
         * @const
         */
        "CHAT_SEND_TEXT" = "CHAT_SEND_TEXT";

    
        /**
         * value: "CALL_PHONE"
         * @const
         */
        "CALL_PHONE" = "CALL_PHONE";

    
        /**
         * value: "OPEN_SHOPPING_ASSISTANT"
         * @const
         */
        "OPEN_SHOPPING_ASSISTANT" = "OPEN_SHOPPING_ASSISTANT";

    
        /**
         * value: "OPEN_SIMPLE_SUBMIT_PAGE"
         * @const
         */
        "OPEN_SIMPLE_SUBMIT_PAGE" = "OPEN_SIMPLE_SUBMIT_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_USER_VERIFICATION_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_USER_VERIFICATION_PAGE" = "PREMIUM_PANEL_OPEN_USER_VERIFICATION_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REFUND_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REFUND_PAGE" = "PREMIUM_PANEL_OPEN_REFUND_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REFUND_DETAILS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REFUND_DETAILS_PAGE" = "PREMIUM_PANEL_OPEN_REFUND_DETAILS_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REFUND_BAZAAR_PAY_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REFUND_BAZAAR_PAY_PAGE" = "PREMIUM_PANEL_OPEN_REFUND_BAZAAR_PAY_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OPEN_REFUND_IBAN_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OPEN_REFUND_IBAN_PAGE" = "PREMIUM_PANEL_OPEN_REFUND_IBAN_PAGE";

    
        /**
         * value: "WEB_FIRST_OPEN_CLIENT_WIDGET_BASE_ACTION"
         * @const
         */
        "WEB_FIRST_OPEN_CLIENT_WIDGET_BASE_ACTION" = "WEB_FIRST_OPEN_CLIENT_WIDGET_BASE_ACTION";

    
        /**
         * value: "PREMIUM_PANEL_BUSINESS_ADDONS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_BUSINESS_ADDONS_PAGE" = "PREMIUM_PANEL_BUSINESS_ADDONS_PAGE";

    
        /**
         * value: "OPEN_FILTER_RANGE_SELECTOR_BOTTOM_SHEET"
         * @const
         */
        "OPEN_FILTER_RANGE_SELECTOR_BOTTOM_SHEET" = "OPEN_FILTER_RANGE_SELECTOR_BOTTOM_SHEET";

    
        /**
         * value: "SUBMIT_POST"
         * @const
         */
        "SUBMIT_POST" = "SUBMIT_POST";

    
        /**
         * value: "OPEN_FILTER_BOTTOM_SHEET"
         * @const
         */
        "OPEN_FILTER_BOTTOM_SHEET" = "OPEN_FILTER_BOTTOM_SHEET";

    
        /**
         * value: "PREMIUM_PANEL_BUSINESS_ADDRESS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_BUSINESS_ADDRESS_PAGE" = "PREMIUM_PANEL_BUSINESS_ADDRESS_PAGE";

    
        /**
         * value: "PAYMENT_OPEN_BAZAAR_PAY_SDK"
         * @const
         */
        "PAYMENT_OPEN_BAZAAR_PAY_SDK" = "PAYMENT_OPEN_BAZAAR_PAY_SDK";

    
        /**
         * value: "PRICING_OPEN_MY_OVERUSAGE_PAGE"
         * @const
         */
        "PRICING_OPEN_MY_OVERUSAGE_PAGE" = "PRICING_OPEN_MY_OVERUSAGE_PAGE";

    
        /**
         * value: "POP_MODAL_PAGE_AND_PERFORM_ACTION"
         * @const
         */
        "POP_MODAL_PAGE_AND_PERFORM_ACTION" = "POP_MODAL_PAGE_AND_PERFORM_ACTION";

    
        /**
         * value: "PREMIUM_PANEL_CHANGE_POST_PRICE_SELECTOR_PAGE"
         * @const
         */
        "PREMIUM_PANEL_CHANGE_POST_PRICE_SELECTOR_PAGE" = "PREMIUM_PANEL_CHANGE_POST_PRICE_SELECTOR_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_CHANGE_POST_PRICE_FORM_PAGE"
         * @const
         */
        "PREMIUM_PANEL_CHANGE_POST_PRICE_FORM_PAGE" = "PREMIUM_PANEL_CHANGE_POST_PRICE_FORM_PAGE";

    
        /**
         * value: "LOAD_GENERAL_OTP_PAGE"
         * @const
         */
        "LOAD_GENERAL_OTP_PAGE" = "LOAD_GENERAL_OTP_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_EMAIL_ADDRESS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_EMAIL_ADDRESS_PAGE" = "PREMIUM_PANEL_EMAIL_ADDRESS_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_LANDLINE_PAGE"
         * @const
         */
        "PREMIUM_PANEL_LANDLINE_PAGE" = "PREMIUM_PANEL_LANDLINE_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_INSIGHT_POST_LIST_PAGE"
         * @const
         */
        "PREMIUM_PANEL_INSIGHT_POST_LIST_PAGE" = "PREMIUM_PANEL_INSIGHT_POST_LIST_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_INSIGHT_POST_DETAIL_PAGE"
         * @const
         */
        "PREMIUM_PANEL_INSIGHT_POST_DETAIL_PAGE" = "PREMIUM_PANEL_INSIGHT_POST_DETAIL_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_FORM_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_FORM_PAGE" = "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_FORM_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE" = "PREMIUM_PANEL_OLD_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE" = "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_DETAILS_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_APPROVE_PAGE"
         * @const
         */
        "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_APPROVE_PAGE" = "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_APPROVE_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_CONFIRM_FORM_PAGE"
         * @const
         */
        "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_CONFIRM_FORM_PAGE" = "PREMIUM_PANEL_NEW_OWNER_TRANSFER_OWNERSHIP_CONFIRM_FORM_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_AUTO_PROMOTION_PAGE"
         * @const
         */
        "PREMIUM_PANEL_AUTO_PROMOTION_PAGE" = "PREMIUM_PANEL_AUTO_PROMOTION_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_AUTO_PROMOTION_DETAILS_PAGE"
         * @const
         */
        "PREMIUM_PANEL_AUTO_PROMOTION_DETAILS_PAGE" = "PREMIUM_PANEL_AUTO_PROMOTION_DETAILS_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_AUTO_PROMOTION_CHOOSE_POST"
         * @const
         */
        "PREMIUM_PANEL_AUTO_PROMOTION_CHOOSE_POST" = "PREMIUM_PANEL_AUTO_PROMOTION_CHOOSE_POST";

    
        /**
         * value: "PREMIUM_PANEL_AUTO_PROMOTION_REGISTER_FORM_PAGE"
         * @const
         */
        "PREMIUM_PANEL_AUTO_PROMOTION_REGISTER_FORM_PAGE" = "PREMIUM_PANEL_AUTO_PROMOTION_REGISTER_FORM_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_USER_REGISTRATION_FORM"
         * @const
         */
        "PREMIUM_PANEL_USER_REGISTRATION_FORM" = "PREMIUM_PANEL_USER_REGISTRATION_FORM";

    
        /**
         * value: "OPEN_LIVE_SESSION_PAGE"
         * @const
         */
        "OPEN_LIVE_SESSION_PAGE" = "OPEN_LIVE_SESSION_PAGE";

    
        /**
         * value: "MY_DIVAR_PAYMENTS"
         * @const
         */
        "MY_DIVAR_PAYMENTS" = "MY_DIVAR_PAYMENTS";

    
        /**
         * value: "PREMIUM_PANEL_REMOVE_BRAND_PAGE"
         * @const
         */
        "PREMIUM_PANEL_REMOVE_BRAND_PAGE" = "PREMIUM_PANEL_REMOVE_BRAND_PAGE";

    
        /**
         * value: "PREMIUM_PANEL_PERSONAL_PAYMENT"
         * @const
         */
        "PREMIUM_PANEL_PERSONAL_PAYMENT" = "PREMIUM_PANEL_PERSONAL_PAYMENT";

    
        /**
         * value: "REGISTER_PASSKEY"
         * @const
         */
        "REGISTER_PASSKEY" = "REGISTER_PASSKEY";

    
        /**
         * value: "LOGIN_WITH_PASSKEY"
         * @const
         */
        "LOGIN_WITH_PASSKEY" = "LOGIN_WITH_PASSKEY";

    
        /**
         * value: "LOGIN_SEND_OTP"
         * @const
         */
        "LOGIN_SEND_OTP" = "LOGIN_SEND_OTP";

    
        /**
         * value: "MY_DIVAR_PAGE"
         * @const
         */
        "MY_DIVAR_PAGE" = "MY_DIVAR_PAGE";

    
        /**
         * value: "OPEN_PROMOTION_FORM_PAGE"
         * @const
         */
        "OPEN_PROMOTION_FORM_PAGE" = "OPEN_PROMOTION_FORM_PAGE";

    

    /**
    * Returns a <code>WidgetsActionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/WidgetsActionType} The enum <code>WidgetsActionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

