/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EventsRegisterEventSubscriptionRequest from '../model/EventsRegisterEventSubscriptionRequest';
import GooglerpcStatus from '../model/GooglerpcStatus';

/**
* Events service.
* @module api/EventsApi
* @version 0.1.0
*/
export default class EventsApi {

    /**
    * Constructs a new EventsApi. 
    * @alias module:api/EventsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * اشتراک در رویداد
     * این API امکان اشتراک در رویدادها برای دریافت اعلان‌ها از طریق webhook هنگام وقوع رویدادها را فراهم می‌کند. پس از اشتراک، هنگام وقوع رویداد مربوطه در آدرس webhook شما مطلع خواهید شد.  **نکات مهم**: - برای رویداد `NEW_MESSAGE_ON_POST`: نیاز به اسکوپ `CHAT_POST_CONVERSATIONS_READ.post_token` یا `CHAT_SUPPLIER_ALL_CONVERSATIONS_READ` - برای رویداد `POST_UPDATE`: نیاز به اسکوپ `USER_POSTS_GET` - آدرس webhook باید در پنل ارائه‌دهندگان برای اپلیکیشن شما تنظیم شده باشد - برخی رویدادها به صورت پیش‌فرض فعال هستند و نیازی به اشتراک ندارند (مثل پیام‌های ربات چت)  #### دسترسی‌ها:  ##### مجوزهای API Key مورد نیاز:  - `EVENTS_REGISTER_SUBSCRIPTION`  ##### OAuth اسکوپ موردنیاز:  - `CHAT_POST_CONVERSATIONS_READ.post_token` یا `CHAT_SUPPLIER_ALL_CONVERSATIONS_READ` یا `USER_POSTS_GET`
     * @param {module:model/EventsRegisterEventSubscriptionRequest} eventsRegisterEventSubscriptionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    eventsRegisterEventSubscriptionWithHttpInfo(eventsRegisterEventSubscriptionRequest) {
      let postBody = eventsRegisterEventSubscriptionRequest;
      // verify the required parameter 'eventsRegisterEventSubscriptionRequest' is set
      if (eventsRegisterEventSubscriptionRequest === undefined || eventsRegisterEventSubscriptionRequest === null) {
        throw new Error("Missing the required parameter 'eventsRegisterEventSubscriptionRequest' when calling eventsRegisterEventSubscription");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey', 'OAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/open-platform/events/subscriptions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * اشتراک در رویداد
     * این API امکان اشتراک در رویدادها برای دریافت اعلان‌ها از طریق webhook هنگام وقوع رویدادها را فراهم می‌کند. پس از اشتراک، هنگام وقوع رویداد مربوطه در آدرس webhook شما مطلع خواهید شد.  **نکات مهم**: - برای رویداد `NEW_MESSAGE_ON_POST`: نیاز به اسکوپ `CHAT_POST_CONVERSATIONS_READ.post_token` یا `CHAT_SUPPLIER_ALL_CONVERSATIONS_READ` - برای رویداد `POST_UPDATE`: نیاز به اسکوپ `USER_POSTS_GET` - آدرس webhook باید در پنل ارائه‌دهندگان برای اپلیکیشن شما تنظیم شده باشد - برخی رویدادها به صورت پیش‌فرض فعال هستند و نیازی به اشتراک ندارند (مثل پیام‌های ربات چت)  #### دسترسی‌ها:  ##### مجوزهای API Key مورد نیاز:  - `EVENTS_REGISTER_SUBSCRIPTION`  ##### OAuth اسکوپ موردنیاز:  - `CHAT_POST_CONVERSATIONS_READ.post_token` یا `CHAT_SUPPLIER_ALL_CONVERSATIONS_READ` یا `USER_POSTS_GET`
     * @param {module:model/EventsRegisterEventSubscriptionRequest} eventsRegisterEventSubscriptionRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    eventsRegisterEventSubscription(eventsRegisterEventSubscriptionRequest) {
      return this.eventsRegisterEventSubscriptionWithHttpInfo(eventsRegisterEventSubscriptionRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ارسال رویداد به کاربر
     * این API امکان ارسال اعلان رویداد به یک کاربر را فراهم می‌کند. رویداد می‌تواند به یک کاربر خاص یا یک آگهی هدف‌گیری شود. رویدادها می‌توانند شامل دکمه‌هایی با اقدامات سفارشی باشند که به کاربران امکان تعامل با اپلیکیشن شما را می‌دهند.  **نکات مهم**: - عنوان دکمه‌ها باید بین 5 تا 50 کاراکتر باشد - هنگام هدف‌گیری کاربر، target_resource_id باید با شناسه مبهم شده کاربر احراز هویت شده مطابقت داشته باشد - هنگام هدف‌گیری آگهی، آگهی باید متعلق به کاربر احراز هویت شده باشد  #### دسترسی‌ها:  ##### مجوزهای API Key مورد نیاز:  - `EVENTS_SEND`  ##### OAuth اسکوپ موردنیاز:  - `SEND_EVENT`
     * @param {Object} opts Optional parameters
     * @param {String} [message] پیام رویداد برای نمایش به کاربر
     * @param {module:model/String} [targetType] هدف رویداد؛ USER یا POST
     * @param {String} [targetResourceId] شناسه هدف. اگر نوع هدف USER است، باید شناسه کاربر دیوار باشد و اگر POST است، باید توکن آگهی باشد.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    eventsSendEventWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'message': opts['message'],
        'target_type': opts['targetType'],
        'target_resource_id': opts['targetResourceId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey', 'OAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/experimental/open-platform/events/send', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ارسال رویداد به کاربر
     * این API امکان ارسال اعلان رویداد به یک کاربر را فراهم می‌کند. رویداد می‌تواند به یک کاربر خاص یا یک آگهی هدف‌گیری شود. رویدادها می‌توانند شامل دکمه‌هایی با اقدامات سفارشی باشند که به کاربران امکان تعامل با اپلیکیشن شما را می‌دهند.  **نکات مهم**: - عنوان دکمه‌ها باید بین 5 تا 50 کاراکتر باشد - هنگام هدف‌گیری کاربر، target_resource_id باید با شناسه مبهم شده کاربر احراز هویت شده مطابقت داشته باشد - هنگام هدف‌گیری آگهی، آگهی باید متعلق به کاربر احراز هویت شده باشد  #### دسترسی‌ها:  ##### مجوزهای API Key مورد نیاز:  - `EVENTS_SEND`  ##### OAuth اسکوپ موردنیاز:  - `SEND_EVENT`
     * @param {Object} opts Optional parameters
     * @param {String} opts.message پیام رویداد برای نمایش به کاربر
     * @param {module:model/String} opts.targetType هدف رویداد؛ USER یا POST
     * @param {String} opts.targetResourceId شناسه هدف. اگر نوع هدف USER است، باید شناسه کاربر دیوار باشد و اگر POST است، باید توکن آگهی باشد.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    eventsSendEvent(opts) {
      return this.eventsSendEventWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
