/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GooglerpcStatus from '../model/GooglerpcStatus';
import PostEditPostBody from '../model/PostEditPostBody';
import PostGetImageUploadURLResponse from '../model/PostGetImageUploadURLResponse';

/**
* Post service.
* @module api/PostApi
* @version 0.1.0
*/
export default class PostApi {

    /**
    * Constructs a new PostApi. 
    * @alias module:api/PostApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Edit a post
     * This API allows you to edit a post. This needs `POST_EDIT.{post_token}` OAuth scope. By now you can only edit title, description, and images of a post.
     * @param {String} postToken 
     * @param {module:model/PostEditPostBody} postEditPostBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    postEditPostWithHttpInfo(postToken, postEditPostBody) {
      let postBody = postEditPostBody;
      // verify the required parameter 'postToken' is set
      if (postToken === undefined || postToken === null) {
        throw new Error("Missing the required parameter 'postToken' when calling postEditPost");
      }
      // verify the required parameter 'postEditPostBody' is set
      if (postEditPostBody === undefined || postEditPostBody === null) {
        throw new Error("Missing the required parameter 'postEditPostBody' when calling postEditPost");
      }

      let pathParams = {
        'post_token': postToken
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/open-platform/post/{post_token}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Edit a post
     * This API allows you to edit a post. This needs `POST_EDIT.{post_token}` OAuth scope. By now you can only edit title, description, and images of a post.
     * @param {String} postToken 
     * @param {module:model/PostEditPostBody} postEditPostBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    postEditPost(postToken, postEditPostBody) {
      return this.postEditPostWithHttpInfo(postToken, postEditPostBody)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get image upload URL
     * This API allows you to get an upload URL for uploading images of a post. You can upload images to the returned URL using a POST request with binary encoding.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostGetImageUploadURLResponse} and HTTP response
     */
    postGetImageUploadURLWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PostGetImageUploadURLResponse;
      return this.apiClient.callApi(
        '/v1/open-platform/post/image-upload-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get image upload URL
     * This API allows you to get an upload URL for uploading images of a post. You can upload images to the returned URL using a POST request with binary encoding.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostGetImageUploadURLResponse}
     */
    postGetImageUploadURL() {
      return this.postGetImageUploadURLWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
