/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GooglerpcStatus from '../model/GooglerpcStatus';
import PostEditPostBody from '../model/PostEditPostBody';
import PostGetImageUploadURLResponse from '../model/PostGetImageUploadURLResponse';
import PostGetPostStatsResponse from '../model/PostGetPostStatsResponse';
import PostSubmitPostRequest from '../model/PostSubmitPostRequest';
import PostSubmitPostResponse from '../model/PostSubmitPostResponse';
import PostSubmitPostV2Request from '../model/PostSubmitPostV2Request';
import PostSubmitUserPostRequest from '../model/PostSubmitUserPostRequest';

/**
* Post service.
* @module api/PostApi
* @version 0.1.0
*/
export default class PostApi {

    /**
    * Constructs a new PostApi. 
    * @alias module:api/PostApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * ویرایش آگهی
     * این API به شما امکان ویرایش آگهی را می‌دهد. این نیاز به دامنه OAuth `POST_EDIT.{post_token}` دارد. در حال حاضر فقط می‌توانید عنوان، توضیحات و تصاویر آگهی را ویرایش کنید.
     * @param {String} postToken 
     * @param {module:model/PostEditPostBody} postEditPostBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    postEditPostWithHttpInfo(postToken, postEditPostBody) {
      let postBody = postEditPostBody;
      // verify the required parameter 'postToken' is set
      if (postToken === undefined || postToken === null) {
        throw new Error("Missing the required parameter 'postToken' when calling postEditPost");
      }
      // verify the required parameter 'postEditPostBody' is set
      if (postEditPostBody === undefined || postEditPostBody === null) {
        throw new Error("Missing the required parameter 'postEditPostBody' when calling postEditPost");
      }

      let pathParams = {
        'post_token': postToken
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/v1/open-platform/post/{post_token}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ویرایش آگهی
     * این API به شما امکان ویرایش آگهی را می‌دهد. این نیاز به دامنه OAuth `POST_EDIT.{post_token}` دارد. در حال حاضر فقط می‌توانید عنوان، توضیحات و تصاویر آگهی را ویرایش کنید.
     * @param {String} postToken 
     * @param {module:model/PostEditPostBody} postEditPostBody 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    postEditPost(postToken, postEditPostBody) {
      return this.postEditPostWithHttpInfo(postToken, postEditPostBody)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * دریافت URL آپلود تصویر
     * این API به شما امکان دریافت URL آپلود برای آپلود تصاویر آگهی را می‌دهد. می‌توانید تصاویر را با استفاده از درخواست POST با کدگذاری باینری به URL برگشتی آپلود کنید.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostGetImageUploadURLResponse} and HTTP response
     */
    postGetImageUploadURLWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PostGetImageUploadURLResponse;
      return this.apiClient.callApi(
        '/v1/open-platform/post/image-upload-url', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * دریافت URL آپلود تصویر
     * این API به شما امکان دریافت URL آپلود برای آپلود تصاویر آگهی را می‌دهد. می‌توانید تصاویر را با استفاده از درخواست POST با کدگذاری باینری به URL برگشتی آپلود کنید.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostGetImageUploadURLResponse}
     */
    postGetImageUploadURL() {
      return this.postGetImageUploadURLWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * دریافت آمارهای آگهی
     * از این api برای مشاهده‌ی آمارهای یک آگهی (مانند تعداد بازدید‌های آگهی) استفاده کنید. 
     * @param {String} postToken توکن آگهی
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostGetPostStatsResponse} and HTTP response
     */
    postGetPostStatsWithHttpInfo(postToken) {
      let postBody = null;
      // verify the required parameter 'postToken' is set
      if (postToken === undefined || postToken === null) {
        throw new Error("Missing the required parameter 'postToken' when calling postGetPostStats");
      }

      let pathParams = {
        'post_token': postToken
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PostGetPostStatsResponse;
      return this.apiClient.callApi(
        '/experimental/open-platform/posts/{post_token}/stats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * دریافت آمارهای آگهی
     * از این api برای مشاهده‌ی آمارهای یک آگهی (مانند تعداد بازدید‌های آگهی) استفاده کنید. 
     * @param {String} postToken توکن آگهی
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostGetPostStatsResponse}
     */
    postGetPostStats(postToken) {
      return this.postGetPostStatsWithHttpInfo(postToken)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ثبت آگهی
     * این API به شما امکان ثبت آگهی را می‌دهد. این نیاز به دامنه OAuth `POST_SUBMIT` دارد. می‌توانید آگهی را با عنوان، توضیحات، تصاویر و سایر فیلدها ثبت کنید. فیلدهای عمومی و فیلدهای مخصوص دسته‌بندی وجود دارند.
     * @param {module:model/PostSubmitPostRequest} postSubmitPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostSubmitPostResponse} and HTTP response
     */
    postSubmitPostWithHttpInfo(postSubmitPostRequest) {
      let postBody = postSubmitPostRequest;
      // verify the required parameter 'postSubmitPostRequest' is set
      if (postSubmitPostRequest === undefined || postSubmitPostRequest === null) {
        throw new Error("Missing the required parameter 'postSubmitPostRequest' when calling postSubmitPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostSubmitPostResponse;
      return this.apiClient.callApi(
        '/experimental/open-platform/posts/new', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ثبت آگهی
     * این API به شما امکان ثبت آگهی را می‌دهد. این نیاز به دامنه OAuth `POST_SUBMIT` دارد. می‌توانید آگهی را با عنوان، توضیحات، تصاویر و سایر فیلدها ثبت کنید. فیلدهای عمومی و فیلدهای مخصوص دسته‌بندی وجود دارند.
     * @param {module:model/PostSubmitPostRequest} postSubmitPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostSubmitPostResponse}
     */
    postSubmitPost(postSubmitPostRequest) {
      return this.postSubmitPostWithHttpInfo(postSubmitPostRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ثبت آگهی با استفاده از اعتبارسنجی ساختار JSON
     * این API به شما امکان ثبت آگهی با استفاده از اعتبارسنجی طرح JSON را می‌دهد. این به مجوز `POST_SUBMIT` نیاز دارد. شما داده‌های کامل آگهی را به عنوان یک رشته JSON ارائه می‌دهید که با احترام به طرح ثبت برای دسته‌بندی مشخص شده موجود در دارایی‌ها اعتبارسنجی خواهد شد.
     * @param {module:model/PostSubmitPostV2Request} postSubmitPostV2Request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostSubmitPostResponse} and HTTP response
     */
    postSubmitPostV2WithHttpInfo(postSubmitPostV2Request) {
      let postBody = postSubmitPostV2Request;
      // verify the required parameter 'postSubmitPostV2Request' is set
      if (postSubmitPostV2Request === undefined || postSubmitPostV2Request === null) {
        throw new Error("Missing the required parameter 'postSubmitPostV2Request' when calling postSubmitPostV2");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostSubmitPostResponse;
      return this.apiClient.callApi(
        '/experimental/open-platform/posts/new-v2', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ثبت آگهی با استفاده از اعتبارسنجی ساختار JSON
     * این API به شما امکان ثبت آگهی با استفاده از اعتبارسنجی طرح JSON را می‌دهد. این به مجوز `POST_SUBMIT` نیاز دارد. شما داده‌های کامل آگهی را به عنوان یک رشته JSON ارائه می‌دهید که با احترام به طرح ثبت برای دسته‌بندی مشخص شده موجود در دارایی‌ها اعتبارسنجی خواهد شد.
     * @param {module:model/PostSubmitPostV2Request} postSubmitPostV2Request 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostSubmitPostResponse}
     */
    postSubmitPostV2(postSubmitPostV2Request) {
      return this.postSubmitPostV2WithHttpInfo(postSubmitPostV2Request)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * ثبت آگهی به عنوان کاربر
     * این API به شما امکان ثبت آگهی از طرف یک کاربر احراز هویت شده با استفاده از اعتبارسنجی طرح JSON را می‌دهد. این به احراز هویت OAuth با توکن دسترسی معتبر و دامنه OAuth `SUBMIT_USER_POST` نیاز دارد. بر خلاف SubmitPostV2 که آگهی‌ها را به عنوان ارائه‌دهنده ثبت می‌کند، این نقطه پایانی آگهی‌ها را به عنوان کاربر مرتبط با توکن دسترسی ارائه شده ثبت می‌کند. آگهی متعلق به کاربر احراز هویت شده خواهد بود. شما داده‌های کامل آگهی را به عنوان یک رشته JSON ارائه می‌دهید که با احترام به طرح ثبت برای دسته‌بندی مشخص شده موجود در دارایی‌ها اعتبارسنجی خواهد شد.
     * @param {module:model/PostSubmitUserPostRequest} postSubmitUserPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/PostSubmitPostResponse} and HTTP response
     */
    postSubmitUserPostWithHttpInfo(postSubmitUserPostRequest) {
      let postBody = postSubmitUserPostRequest;
      // verify the required parameter 'postSubmitUserPostRequest' is set
      if (postSubmitUserPostRequest === undefined || postSubmitUserPostRequest === null) {
        throw new Error("Missing the required parameter 'postSubmitUserPostRequest' when calling postSubmitUserPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['APIKey'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostSubmitPostResponse;
      return this.apiClient.callApi(
        '/experimental/open-platform/user-posts/new', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * ثبت آگهی به عنوان کاربر
     * این API به شما امکان ثبت آگهی از طرف یک کاربر احراز هویت شده با استفاده از اعتبارسنجی طرح JSON را می‌دهد. این به احراز هویت OAuth با توکن دسترسی معتبر و دامنه OAuth `SUBMIT_USER_POST` نیاز دارد. بر خلاف SubmitPostV2 که آگهی‌ها را به عنوان ارائه‌دهنده ثبت می‌کند، این نقطه پایانی آگهی‌ها را به عنوان کاربر مرتبط با توکن دسترسی ارائه شده ثبت می‌کند. آگهی متعلق به کاربر احراز هویت شده خواهد بود. شما داده‌های کامل آگهی را به عنوان یک رشته JSON ارائه می‌دهید که با احترام به طرح ثبت برای دسته‌بندی مشخص شده موجود در دارایی‌ها اعتبارسنجی خواهد شد.
     * @param {module:model/PostSubmitUserPostRequest} postSubmitUserPostRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/PostSubmitPostResponse}
     */
    postSubmitUserPost(postSubmitUserPostRequest) {
      return this.postSubmitUserPostWithHttpInfo(postSubmitUserPostRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
