/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.AddonsWidget();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddonsWidget', function() {
    it('should create an instance of AddonsWidget', function() {
      // uncomment below and update the code to test AddonsWidget
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be.a(KenarApiClient.AddonsWidget);
    });

    it('should have the property buttonBar (base name: "button_bar")', function() {
      // uncomment below and update the code to test the property buttonBar
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property descriptionRow (base name: "description_row")', function() {
      // uncomment below and update the code to test the property descriptionRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property evaluationRow (base name: "evaluation_row")', function() {
      // uncomment below and update the code to test the property evaluationRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property eventRow (base name: "event_row")', function() {
      // uncomment below and update the code to test the property eventRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property groupInfoRow (base name: "group_info_row")', function() {
      // uncomment below and update the code to test the property groupInfoRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property imageCarouselRow (base name: "image_carousel_row")', function() {
      // uncomment below and update the code to test the property imageCarouselRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property scoreRow (base name: "score_row")', function() {
      // uncomment below and update the code to test the property scoreRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property selectorRow (base name: "selector_row")', function() {
      // uncomment below and update the code to test the property selectorRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property semanticPaths (base name: "semantic_paths")', function() {
      // uncomment below and update the code to test the property semanticPaths
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property subtitleRow (base name: "subtitle_row")', function() {
      // uncomment below and update the code to test the property subtitleRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

    it('should have the property titleRow (base name: "title_row")', function() {
      // uncomment below and update the code to test the property titleRow
      //var instance = new KenarApiClient.AddonsWidget();
      //expect(instance).to.be();
    });

  });

}));
