/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.AddonsCreatePostAddonRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddonsCreatePostAddonRequest', function() {
    it('should create an instance of AddonsCreatePostAddonRequest', function() {
      // uncomment below and update the code to test AddonsCreatePostAddonRequest
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be.a(KenarApiClient.AddonsCreatePostAddonRequest);
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property widgets (base name: "widgets")', function() {
      // uncomment below and update the code to test the property widgets
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property selector (base name: "selector")', function() {
      // uncomment below and update the code to test the property selector
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property linkInSpec (base name: "link_in_spec")', function() {
      // uncomment below and update the code to test the property linkInSpec
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property semantic (base name: "semantic")', function() {
      // uncomment below and update the code to test the property semantic
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

    it('should have the property semanticSensitives (base name: "semantic_sensitives")', function() {
      // uncomment below and update the code to test the property semanticSensitives
      //var instance = new KenarApiClient.AddonsCreatePostAddonRequest();
      //expect(instance).to.be();
    });

  });

}));
