/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.ChatapiMessage();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChatapiMessage', function() {
    it('should create an instance of ChatapiMessage', function() {
      // uncomment below and update the code to test ChatapiMessage
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be.a(KenarApiClient.ChatapiMessage);
    });

    it('should have the property conversation (base name: "conversation")', function() {
      // uncomment below and update the code to test the property conversation
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property fileData (base name: "file_data")', function() {
      // uncomment below and update the code to test the property fileData
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property imageData (base name: "image_data")', function() {
      // uncomment below and update the code to test the property imageData
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property locationData (base name: "location_data")', function() {
      // uncomment below and update the code to test the property locationData
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property sentAt (base name: "sent_at")', function() {
      // uncomment below and update the code to test the property sentAt
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property text (base name: "text")', function() {
      // uncomment below and update the code to test the property text
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property videoData (base name: "video_data")', function() {
      // uncomment below and update the code to test the property videoData
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

    it('should have the property voiceData (base name: "voice_data")', function() {
      // uncomment below and update the code to test the property voiceData
      //var instance = new KenarApiClient.ChatapiMessage();
      //expect(instance).to.be();
    });

  });

}));
