/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.FinderSearchQuery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FinderSearchQuery', function() {
    it('should create an instance of FinderSearchQuery', function() {
      // uncomment below and update the code to test FinderSearchQuery
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be.a(KenarApiClient.FinderSearchQuery);
    });

    it('should have the property brandModel (base name: "brand_model")', function() {
      // uncomment below and update the code to test the property brandModel
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property productionYear (base name: "production_year")', function() {
      // uncomment below and update the code to test the property productionYear
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property usage (base name: "usage")', function() {
      // uncomment below and update the code to test the property usage
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property rooms (base name: "rooms")', function() {
      // uncomment below and update the code to test the property rooms
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property rent (base name: "rent")', function() {
      // uncomment below and update the code to test the property rent
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property credit (base name: "credit")', function() {
      // uncomment below and update the code to test the property credit
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

    it('should have the property onlyWithParking (base name: "only_with_parking")', function() {
      // uncomment below and update the code to test the property onlyWithParking
      //var instance = new KenarApiClient.FinderSearchQuery();
      //expect(instance).to.be();
    });

  });

}));
