/**
 * Kenar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.FinderSearchPostItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FinderSearchPostItem', function() {
    it('should create an instance of FinderSearchPostItem', function() {
      // uncomment below and update the code to test FinderSearchPostItem
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be.a(KenarApiClient.FinderSearchPostItem);
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property communityFields (base name: "community_fields")', function() {
      // uncomment below and update the code to test the property communityFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property electronicDevicesFields (base name: "electronic_devices_fields")', function() {
      // uncomment below and update the code to test the property electronicDevicesFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property homeKitchenFields (base name: "home_kitchen_fields")', function() {
      // uncomment below and update the code to test the property homeKitchenFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property jobsFields (base name: "jobs_fields")', function() {
      // uncomment below and update the code to test the property jobsFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedAt (base name: "last_modified_at")', function() {
      // uncomment below and update the code to test the property lastModifiedAt
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property leisureHobbiesFields (base name: "leisure_hobbies_fields")', function() {
      // uncomment below and update the code to test the property leisureHobbiesFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property personalGoodsFields (base name: "personal_goods_fields")', function() {
      // uncomment below and update the code to test the property personalGoodsFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property realEstateFields (base name: "real_estate_fields")', function() {
      // uncomment below and update the code to test the property realEstateFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property servicesFields (base name: "services_fields")', function() {
      // uncomment below and update the code to test the property servicesFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property toolsMaterialsEquipmentFields (base name: "tools_materials_equipment_fields")', function() {
      // uncomment below and update the code to test the property toolsMaterialsEquipmentFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

    it('should have the property vehiclesFields (base name: "vehicles_fields")', function() {
      // uncomment below and update the code to test the property vehiclesFields
      //var instance = new KenarApiClient.FinderSearchPostItem();
      //expect(instance).to.be();
    });

  });

}));
