/**
 * API کنار
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KenarApiClient);
  }
}(this, function(expect, KenarApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KenarApiClient.PostEditPostV2Body();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PostEditPostV2Body', function() {
    it('should create an instance of PostEditPostV2Body', function() {
      // uncomment below and update the code to test PostEditPostV2Body
      //var instance = new KenarApiClient.PostEditPostV2Body();
      //expect(instance).to.be.a(KenarApiClient.PostEditPostV2Body);
    });

    it('should have the property updateMask (base name: "update_mask")', function() {
      // uncomment below and update the code to test the property updateMask
      //var instance = new KenarApiClient.PostEditPostV2Body();
      //expect(instance).to.be();
    });

    it('should have the property categoryData (base name: "category_data")', function() {
      // uncomment below and update the code to test the property categoryData
      //var instance = new KenarApiClient.PostEditPostV2Body();
      //expect(instance).to.be();
    });

    it('should have the property generalData (base name: "general_data")', function() {
      // uncomment below and update the code to test the property generalData
      //var instance = new KenarApiClient.PostEditPostV2Body();
      //expect(instance).to.be();
    });

  });

}));
